export const events = [
  {
    id: "1",
    title: "Navratri Mega Garba 2025",
    description:
      "The largest Navratri celebration in the Bay Area. Nine nights of traditional Raas Garba with live dhol, folk singers, and authentic Gujarati cuisine.",
    location: "San Jose Convention Center, CA",
    city: "San Jose",
    state: "CA",
    date: "2025-10-02",
    endDate: "2025-10-10",
    time: "7:00 PM",
    category: "Garba",
    image: "/images/navratri.jpg",
    price: 35,
    totalTickets: 2000,
    soldTickets: 1450,
    organizer: "Bay Area Gujarati Samaj",
    tags: ["Navratri", "Garba", "Live Music", "Family"],
  },
  {
    id: "2",
    title: "Raas Garba Night — Atlanta",
    description:
      "An electrifying one-night Raas Garba event with DJ and live dhol players. All skill levels welcome — beginners circles available!",
    location: "Georgia World Congress Center, Atlanta, GA",
    city: "Atlanta",
    state: "GA",
    date: "2025-10-05",
    endDate: "2025-10-05",
    time: "6:30 PM",
    category: "Raas",
    image: "/images/raas.jpg",
    price: 25,
    totalTickets: 800,
    soldTickets: 620,
    organizer: "Atlanta Desi Connect",
    tags: ["Raas", "DJ", "Singles Night", "Community"],
  },
  {
    id: "3",
    title: "Chicago Navratri Utsav",
    description:
      "Chicago's premier Navratri festival returns for its 12th year. Traditional attire encouraged. Garba competition with cash prizes on the final night.",
    location: "Rosemont Convention Center, Chicago, IL",
    city: "Chicago",
    state: "IL",
    date: "2025-10-03",
    endDate: "2025-10-11",
    time: "7:30 PM",
    category: "Garba",
    image: "/images/chicago.jpg",
    price: 40,
    totalTickets: 3000,
    soldTickets: 2800,
    organizer: "GUJCOA Chicago",
    tags: ["Navratri", "Competition", "Traditional", "Family"],
  },
  {
    id: "4",
    title: "NYC Garba Nights",
    description:
      "New York City's most vibrant Garba celebration. Multiple floors — traditional circles downstairs, fusion Garba upstairs.",
    location: "Pier 36, New York, NY",
    city: "New York",
    state: "NY",
    date: "2025-10-04",
    endDate: "2025-10-08",
    time: "8:00 PM",
    category: "Garba",
    image: "/images/nyc.jpg",
    price: 50,
    totalTickets: 1500,
    soldTickets: 1500,
    organizer: "South Asian Culture Society NY",
    tags: ["Navratri", "Fusion", "Garba", "NYC"],
  },
  {
    id: "5",
    title: "Dallas Dandiya Dhamaka",
    description:
      "Dandiya Raas at its finest — colorful sticks, vibrant outfits, and a full night of celebration with professional choreographers leading the crowd.",
    location: "Kay Bailey Hutchison Convention Center, Dallas, TX",
    city: "Dallas",
    state: "TX",
    date: "2025-10-06",
    endDate: "2025-10-06",
    time: "7:00 PM",
    category: "Dandiya",
    image: "/images/dallas.jpg",
    price: 30,
    totalTickets: 1200,
    soldTickets: 890,
    organizer: "DFW Gujarati Association",
    tags: ["Dandiya", "Raas", "Family", "Texas"],
  },
  {
    id: "6",
    title: "Seattle Garba Fusion Festival",
    description:
      "Where tradition meets innovation. Garba with live fusion band blending folk music with contemporary beats. Food trucks and cultural booths.",
    location: "Seattle Center, Seattle, WA",
    city: "Seattle",
    state: "WA",
    date: "2025-10-09",
    endDate: "2025-10-09",
    time: "5:00 PM",
    category: "Garba",
    image: "/images/seattle.jpg",
    price: 20,
    totalTickets: 600,
    soldTickets: 310,
    organizer: "Seattle Desi Arts Collective",
    tags: ["Fusion", "Garba", "Family", "Food"],
  },
];

export const communityGroups = [
  {
    id: "1",
    name: "Bay Area Garba Enthusiasts",
    city: "San Jose, CA",
    members: 1240,
    description: "The largest community of Garba dancers in Northern California.",
    category: "Regional",
  },
  {
    id: "2",
    name: "USA Navratri Organizers Network",
    city: "Nationwide",
    members: 320,
    description: "Connect with event organizers across the country to share resources.",
    category: "Organizers",
  },
  {
    id: "3",
    name: "Raas Garba Beginners Circle",
    city: "Nationwide",
    members: 4800,
    description: "New to Garba? This is your safe space to learn, ask questions, and find local classes.",
    category: "Beginners",
  },
  {
    id: "4",
    name: "NYC South Asian Dance Community",
    city: "New York, NY",
    members: 870,
    description: "Bringing together dancers, choreographers, and lovers of South Asian dance in NYC.",
    category: "Regional",
  },
  {
    id: "5",
    name: "Traditional Garba Preservation Society",
    city: "Nationwide",
    members: 590,
    description: "Dedicated to preserving the authentic folk roots of Garba and Dandiya Raas.",
    category: "Cultural",
  },
  {
    id: "6",
    name: "Midwest Desi Celebrations",
    city: "Chicago, IL",
    members: 1100,
    description: "Events, meetups, and festivals for the South Asian community across the Midwest.",
    category: "Regional",
  },
];

export const stats = [
  { label: "Events Hosted", value: "500+" },
  { label: "Community Members", value: "80K+" },
  { label: "Cities Reached", value: "120+" },
  { label: "Tickets Sold", value: "2M+" },
];

export const testimonials = [
  {
    id: "1",
    name: "Priya Patel",
    city: "San Jose, CA",
    text: "Rameelo made finding Navratri events near me so easy. I discovered a garba circle 2 miles from my house that I had no idea existed!",
    avatar: "PP",
  },
  {
    id: "2",
    name: "Rohan Shah",
    city: "Chicago, IL",
    text: "As an organizer, the ticketing tools are incredible. Sold out our 1,200-person event in under a week.",
    avatar: "RS",
  },
  {
    id: "3",
    name: "Meera Desai",
    city: "Atlanta, GA",
    text: "Moved to Atlanta 2 years ago and felt so disconnected from the community. Through Rameelo I found my garba family.",
    avatar: "MD",
  },
];

export const navLinks = [
  { label: "Home", href: "/" },
  { label: "Events", href: "/events" },
  { label: "Community", href: "/community" },
  { label: "Tickets", href: "/tickets" },
  { label: "Pricing", href: "/pricing" },
  { label: "About", href: "/about" },
];
