export interface GarbaEvent {
  id: string;
  title: string;
  artist: string;
  artistSlug: string;
  description: string;
  venue: string;
  city: string;
  state: string;
  date: string;
  dateISO: string;
  time: string;
  category: "Garba" | "Dandiya" | "Disco Dandiya" | "Fusion Garba" | "Traditional Garba" | "Sufi Garba";
  price: number;
  priceVIP?: number;
  totalTickets: number;
  soldTickets: number;
  tags: string[];
  isNavratri: boolean;
  navratriNight?: number;
  featured?: boolean;
}

export interface ArtistSong {
  title: string;
  album: string;
  year: number;
  youtubeId: string;
  streams: string;
}

export interface Artist {
  name: string;
  slug: string;
  title: string;
  initials: string;
  color: string;
  accentColor: string;
  origin: string;
  yearsActive: string;
  genre: string;
  funFact: string;
  bio: string;
  followers: string;
  showsPerformed: number;
  awardsCount: number;
  popularSongs: ArtistSong[];
  youtubeChannel: string;
  instagramHandle: string;
  accolades: string[];
}

export const artists: Artist[] = [
  {
    name: "Falguni Pathak",
    slug: "falguni-pathak",
    title: "Queen of Garba",
    initials: "FP",
    color: "#7C1F2C",
    accentColor: "#f5c6cb",
    origin: "Ahmedabad, Gujarat",
    yearsActive: "1990–present",
    genre: "Traditional Garba",
    funFact: "She turned down a Bollywood playback career in the 90s to stay true to Garba — and sold out Madison Square Garden instead.",
    bio: "Falguni Pathak is the undisputed Queen of Garba, whose voice has defined Navratri for three decades across India and the diaspora. Rising from the chawls of Ahmedabad, she became a festival institution — her devotional yet joyful style drawing millions each year. No Navratri season anywhere in the world feels complete without her.",
    followers: "14.2M",
    showsPerformed: 1200,
    awardsCount: 31,
    youtubeChannel: "UCFalguniPathakOfficial",
    instagramHandle: "@falgunipathak12",
    popularSongs: [
      { title: "Maine Payal Hai Chhankai", album: "Meri Chunar Udd Udd Jaye", year: 1997, youtubeId: "FRdJXBqUE_8", streams: "320M" },
      { title: "O Ri Chori", album: "Aao Milo Chalo", year: 1999, youtubeId: "KX_p_S7yMlM", streams: "180M" },
      { title: "Chudi Jo Khhankai", album: "Dil Ka Kya Kasoor", year: 1997, youtubeId: "9bZkp7q19f0", streams: "150M" },
      { title: "Yaad Piya Ki Aane Lagi", album: "Singles", year: 2000, youtubeId: "e3Mkm0GFSmU", streams: "95M" },
    ],
    accolades: [
      "Screen Award — Best Non-Film Album (1998)",
      "Zee Cine Award — Popular Singer (2000)",
      "3× Navratri Artist of the Year — Times of India",
      "Limca Book of Records — Most Navratri Shows in a Season",
    ],
  },
  {
    name: "Kinjal Dave",
    slug: "kinjal-dave",
    title: "Modern Garba Queen",
    initials: "KD",
    color: "#c47a00",
    accentColor: "#fef3c7",
    origin: "Surat, Gujarat",
    yearsActive: "2012–present",
    genre: "Fusion Garba",
    funFact: "Her YouTube channel hit 1 billion total views before she turned 30 — a first for any Gujarati folk artist.",
    bio: "Kinjal Dave exploded onto the Garba scene in her early twenties with a fearless fusion of folk Garba and contemporary Gujarati pop. Her raw, powerful voice and relatable lyrics about modern Gujarati life earned her a massive Gen-Z following. She regularly collaborates with Bollywood composers while staying fiercely rooted in her folk identity.",
    followers: "9.8M",
    showsPerformed: 620,
    awardsCount: 18,
    youtubeChannel: "UCKinjalDaveOfficial",
    instagramHandle: "@kinjaloficial",
    popularSongs: [
      { title: "Nonstop Garba Medley", album: "Garba Dhamaka Vol. 1", year: 2016, youtubeId: "3JZ_D3ELwOQ", streams: "280M" },
      { title: "Disco Dandiya", album: "Fusion Navratri", year: 2018, youtubeId: "CevxZvSJLk8", streams: "210M" },
      { title: "Aavo Re Ramiye", album: "Folk Pop", year: 2019, youtubeId: "fLexgOxsZu0", streams: "130M" },
      { title: "Kesariya Balam", album: "Folk Covers", year: 2021, youtubeId: "7pcGpm7ALLQ", streams: "88M" },
    ],
    accolades: [
      "Filmfare Award (Gujarati) — Best Female Singer (2018)",
      "YouTube Gold Creator Award",
      "Gujarati Pride Award — Youth Icon (2019)",
      "Forbes India — 30 Under 30 Entertainment (2020)",
    ],
  },
  {
    name: "Geeta Rabari",
    slug: "geeta-rabari",
    title: "Folk Garba Star",
    initials: "GR",
    color: "#0E8C7A",
    accentColor: "#ccfbf1",
    origin: "Kutch, Gujarat",
    yearsActive: "2014–present",
    genre: "Folk Garba",
    funFact: "She learned to sing by mimicking bansuri (flute) melodies as a child in Kutch — you can still hear the flute-like ornamentation in every phrase.",
    bio: "Born in the salt flats of Kutch, Geeta Rabari carries the raw earth of Gujarat in her voice. Discovered on a regional reality show, she pivoted from contest winner to cultural icon almost overnight. Her commitment to authentic Kutchi folk traditions — unfiltered by mainstream production — has made her the darling of purists and newcomers alike.",
    followers: "6.1M",
    showsPerformed: 380,
    awardsCount: 11,
    youtubeChannel: "UCGeetaRabariOfficial",
    instagramHandle: "@geetarabari",
    popularSongs: [
      { title: "Mara Dil Ma Tu", album: "Kutchi Folk", year: 2015, youtubeId: "hT_nvWreIhg", streams: "195M" },
      { title: "O Ri Duniya", album: "Folk Fusion", year: 2017, youtubeId: "1G4isv_Fylg", streams: "140M" },
      { title: "Chalo Garba Ramo", album: "Navratri Special", year: 2019, youtubeId: "RgKAFK5djSk", streams: "90M" },
      { title: "Tara Vina Shyam", album: "Devotional Folk", year: 2020, youtubeId: "OPf0YbXqDm0", streams: "65M" },
    ],
    accolades: [
      "Sa Re Ga Ma Pa (Gujarati) — Winner 2014",
      "Gujarati Film Award — Best Folk Singer (2017)",
      "Kutch Utsav — Cultural Ambassador (2021)",
      "Times of India — 10 Most Influential Gujarati Artists",
    ],
  },
  {
    name: "Aishwarya Majmudar",
    slug: "aishwarya-majmudar",
    title: "Classical Garba Voice",
    initials: "AM",
    color: "#2E1B30",
    accentColor: "#ede9fe",
    origin: "Vadodara, Gujarat",
    yearsActive: "2005–present",
    genre: "Classical Garba",
    funFact: "She holds a degree in Hindustani classical music from M.S. University Baroda — the same institution that produced Ravi Shankar's students.",
    bio: "Aishwarya Majmudar is the rare artist who bridges the rigorous world of Hindustani classical music with the celebratory energy of Navratri Garba. Her training under legendary gurus in Vadodara gives her voice a depth and precision that few folk artists can match. She is celebrated for bringing ragas like Bhairavi and Yaman into the Garba tradition.",
    followers: "3.4M",
    showsPerformed: 290,
    awardsCount: 14,
    youtubeChannel: "UCAishwaryaMajmudar",
    instagramHandle: "@aishwaryamajmudar",
    popularSongs: [
      { title: "Raga Bhairavi Garba", album: "Classical Navratri", year: 2009, youtubeId: "QkF3oxziZZo", streams: "45M" },
      { title: "Jai Jai Garvi Gujarat", album: "Devotional", year: 2012, youtubeId: "HgzGwKwLmgM", streams: "62M" },
      { title: "Naveli Navratri", album: "Festival Special", year: 2015, youtubeId: "j5-yKhDd64s", streams: "38M" },
      { title: "Ambaji Na Dham", album: "Shakti Bhakti", year: 2018, youtubeId: "9bZkp7q19f0", streams: "29M" },
    ],
    accolades: [
      "Sur Mani Award — Sur Singar Samsad (2008)",
      "National Folk Award — Ministry of Culture (2013)",
      "Vadodara Music Circle — Lifetime Achievement (2022)",
      "Best Classical Garba Vocalist — Navratri Utsav Award (5× consecutive)",
    ],
  },
  {
    name: "Hemant Chauhan",
    slug: "hemant-chauhan",
    title: "Garba Maestro",
    initials: "HC",
    color: "#D4891B",
    accentColor: "#fef9c3",
    origin: "Rajkot, Gujarat",
    yearsActive: "1978–present",
    genre: "Traditional Garba",
    funFact: "He has performed Navratri Garba for 46 consecutive years without ever missing a single season — earning him the unofficial title 'The Iron Voice of Gujarat.'",
    bio: "Hemant Chauhan is a living legend whose career spans nearly five decades and four generations of Garba lovers. Starting in the age of cassette tapes in the late 1970s, he adapted through vinyl, CD, MP3, and streaming without ever diluting his traditional Saurashtra Garba sound. His baritone is instantly recognizable and considered a national cultural treasure.",
    followers: "5.2M",
    showsPerformed: 2100,
    awardsCount: 47,
    youtubeChannel: "UCHemantChauhanOfficial",
    instagramHandle: "@hemantchauhan_official",
    popularSongs: [
      { title: "Mara Sohamna Navratri", album: "Navratri Utsav Vol. 1", year: 1982, youtubeId: "kXYiU_JCYtU", streams: "55M" },
      { title: "Ramva Aavo Maheshwari", album: "Saurashtra Garba", year: 1989, youtubeId: "YqeW9_5kURI", streams: "48M" },
      { title: "Jogi Thakor", album: "Bhakti Sangeet", year: 1995, youtubeId: "IcrbM1l_BoI", streams: "72M" },
      { title: "Nonstop Garba 9 Raat", album: "Navratri Live", year: 2002, youtubeId: "2vjPBrBU-TM", streams: "41M" },
    ],
    accolades: [
      "Padma Shri — Government of India (2019)",
      "Gujarat Ratna Award (2015)",
      "Sangeet Natak Akademi Award (2011)",
      "47× Navratri Season Performer — Guinness World Records nominee",
    ],
  },
  {
    name: "Atul Purohit",
    slug: "atul-purohit",
    title: "Garba Legend",
    initials: "AP",
    color: "#3D2543",
    accentColor: "#f3e8ff",
    origin: "Ahmedabad, Gujarat",
    yearsActive: "1985–present",
    genre: "Traditional Garba",
    funFact: "He composed the definitive 'raas' arrangement still used as the template for every Navratri competition across North America.",
    bio: "Atul Purohit's contribution to Garba goes far beyond performance — he is a composer, arranger, and cultural custodian who literally wrote the rulebook on modern Navratri raas competitions. His arrangements have trained thousands of dancers and his orchestral Garba style, blending traditional dhol with symphonic strings, is widely imitated but never matched.",
    followers: "4.7M",
    showsPerformed: 850,
    awardsCount: 22,
    youtubeChannel: "UCAtulPurohitOfficial",
    instagramHandle: "@atulpurohit_garba",
    popularSongs: [
      { title: "Raas Utsav Medley", album: "Navratri Celebration", year: 1992, youtubeId: "XGBoh7Lp2eU", streams: "58M" },
      { title: "Nonstop Raas Vol. 3", album: "Raas Rangilo", year: 1998, youtubeId: "wncoRejhMIs", streams: "43M" },
      { title: "Dhol Nagara Vage", album: "Festival Beats", year: 2004, youtubeId: "dQw4w9WgXcQ", streams: "31M" },
      { title: "Garba Ni Raat", album: "Live at Ahmedabad", year: 2010, youtubeId: "y6120QOlsfU", streams: "27M" },
    ],
    accolades: [
      "Gujarat Sangeet Academy Award (2001)",
      "Best Traditional Garba Composer — Navratri Utsav (7× winner)",
      "Rotary Club — Cultural Excellence Award (2016)",
      "Times of India — Gujarat Cultural Icon (2018)",
    ],
  },
  {
    name: "Osman Mir",
    slug: "osman-mir",
    title: "Sufi & Folk Master",
    initials: "OM",
    color: "#0a4f46",
    accentColor: "#ccfbf1",
    origin: "Patan, Gujarat",
    yearsActive: "2000–present",
    genre: "Sufi Garba",
    funFact: "His rendition of 'Bolo Tara Ra Ra' at the UNESCO World Music Festival in Paris is the most-streamed live performance by any Gujarati artist globally.",
    bio: "Osman Mir is the rare voice that transcends genre, community, and border. A Muslim artist who has become one of the most beloved Garba performers, his Sufi-infused take on traditional folk songs dissolves every boundary. His performances are less concerts and more spiritual experiences — silence in a 10,000-person crowd is his signature effect.",
    followers: "2.9M",
    showsPerformed: 410,
    awardsCount: 16,
    youtubeChannel: "UCOsmanMirOfficial",
    instagramHandle: "@osmanmir_official",
    popularSongs: [
      { title: "Bolo Tara Ra Ra", album: "Sufi Garba", year: 2003, youtubeId: "L_jWHffIx5E", streams: "78M" },
      { title: "Vande Mataram (Garba Mix)", album: "Desh Bhakti Folk", year: 2007, youtubeId: "SXkSXR9QMNY", streams: "52M" },
      { title: "Pir Mohammad", album: "Sufi Masters", year: 2011, youtubeId: "5NV6Rdv1h3Q", streams: "44M" },
      { title: "Garbo Kheliye", album: "Folk Fusion Live", year: 2016, youtubeId: "OfkQlZArFzg", streams: "33M" },
    ],
    accolades: [
      "UNESCO Intangible Heritage Performer (2015)",
      "National Integration Award — Ministry of Culture (2012)",
      "Sufi Music Award — Best Folk Fusion (2009)",
      "Harmony Foundation Award — Communal Harmony (2018)",
    ],
  },
  {
    name: "Rekha Trivedi",
    slug: "rekha-trivedi",
    title: "Traditional Garba",
    initials: "RT",
    color: "#892240",
    accentColor: "#fce7f3",
    origin: "Surat, Gujarat",
    yearsActive: "1993–present",
    genre: "Traditional Garba",
    funFact: "She has taught over 40,000 women the traditional Garba foot-work patterns through her free 'Raas Shikshan' camps across rural Gujarat.",
    bio: "Rekha Trivedi is as much an educator as she is a performer. Her life's mission is the preservation and transmission of traditional Garba forms that predate Bollywood influence — patterns and rhythms from village traditions going back centuries. She performs with barefoot dancers, no amplification in rural settings, and full orchestral spectacle in stadium shows, equally at home in both.",
    followers: "2.1M",
    showsPerformed: 560,
    awardsCount: 19,
    youtubeChannel: "UCRekhaTrivediOfficial",
    instagramHandle: "@rekhatrivedi_garba",
    popularSongs: [
      { title: "Rame Re Rame Garba", album: "Village Traditions Vol. 1", year: 1996, youtubeId: "CkZyZFa5gZE", streams: "29M" },
      { title: "Ambaji Maa Na Garba", album: "Shakti Stuti", year: 2001, youtubeId: "nfWlot6h_JM", streams: "41M" },
      { title: "Navratri Ni Raat", album: "Nonstop Traditional", year: 2006, youtubeId: "9bZkp7q19f0", streams: "35M" },
      { title: "Dhol Dholki Vagadd", album: "Drum Traditions", year: 2012, youtubeId: "YZmx75LR1_s", streams: "18M" },
    ],
    accolades: [
      "Sahitya Kala Parishad Award (2007)",
      "Gujarat Tourism Cultural Ambassador (2014–present)",
      "Padma Bhushan nominee (2020)",
      "National Women's Day Award — Cultural Preservation (2019)",
    ],
  },
  {
    name: "Sachin-Jigar",
    slug: "sachin-jigar",
    title: "Bollywood Fusion",
    initials: "SJ",
    color: "#5a1e7a",
    accentColor: "#faf5ff",
    origin: "Baroda / Mumbai",
    yearsActive: "2006–present",
    genre: "Bollywood Fusion",
    funFact: "The duo originally met at a corporate jingle recording session in 2004 and bonded over a shared love of Garba — two years later they had a Filmfare Award.",
    bio: "Sachin–Jigar are the Bollywood duo who proved that Garba could headline multiplex screens as well as festival grounds. Their film scores brought Garba rhythms into mainstream Hindi cinema (Shuddh Desi Romance, Sui Dhaaga), introducing the sound to hundreds of millions who had never attended Navratri. Their live shows blend film song energy with authentic Garba instrumentation.",
    followers: "8.3M",
    showsPerformed: 340,
    awardsCount: 26,
    youtubeChannel: "UCSachinJigarOfficial",
    instagramHandle: "@sachinjigar",
    popularSongs: [
      { title: "Manja", album: "Kai Po Che OST", year: 2013, youtubeId: "5QFDrY4qLCg", streams: "320M" },
      { title: "Lat Lag Gayee", album: "Race 2 OST", year: 2013, youtubeId: "8UCUL9nMBFE", streams: "290M" },
      { title: "Chali Kaatni Meri", album: "Sui Dhaaga OST", year: 2018, youtubeId: "xKSCFM3JMFE", streams: "180M" },
      { title: "Garba Medley Live", album: "Navratri Live 2022", year: 2022, youtubeId: "mgyeWhN-jSQ", streams: "75M" },
    ],
    accolades: [
      "Filmfare Award — Best Music Album (2013, 2018)",
      "IIFA Award — Outstanding Achievement in Music (2017)",
      "Screen Award — Best Background Score (2016)",
      "Mirchi Music Award — Album of the Year (3× winner)",
    ],
  },
  {
    name: "Parthiv Gohil",
    slug: "parthiv-gohil",
    title: "Playback & Garba",
    initials: "PG",
    color: "#1a4a5e",
    accentColor: "#e0f2fe",
    origin: "Bhavnagar, Gujarat",
    yearsActive: "2002–present",
    genre: "Playback & Garba",
    funFact: "He was offered a seat at IIT Kharagpur but chose to move to Mumbai and chase music — his first Bollywood track came out 18 months later.",
    bio: "Parthiv Gohil is the most successful Bollywood playback singer to have emerged from the Garba tradition. His silky tenor graced over 200 Bollywood films while simultaneously recording some of the most beloved Navratri albums of the 2000s. He is the living proof that classical rigor, folk authenticity, and film industry demands can coexist in one extraordinary voice.",
    followers: "4.1M",
    showsPerformed: 480,
    awardsCount: 21,
    youtubeChannel: "UCParthivGohilOfficial",
    instagramHandle: "@parthivgohil",
    popularSongs: [
      { title: "Ek Dilruba Hai", album: "Bewafaa OST", year: 2005, youtubeId: "BjhZ-zhG78I", streams: "140M" },
      { title: "Tujh Mein Rab Dikhta Hai", album: "Rab Ne Bana Di Jodi OST", year: 2008, youtubeId: "OfkQlZArFzg", streams: "380M" },
      { title: "Navratri Nonstop", album: "Garba Utsav", year: 2011, youtubeId: "7lQ8zugaanu", streams: "65M" },
      { title: "Sarveshwar Mahadeva", album: "Bhakti Sangeet", year: 2014, youtubeId: "YR5ApYxkU-U", streams: "50M" },
    ],
    accolades: [
      "Filmfare Award — Best Male Playback Singer (2009)",
      "GIMA Award — Best Gujarati Artist (2014)",
      "Sur Sangam Award — Lifetime Achievement (2021)",
      "National Folk Association — Excellence in Playback (2016)",
    ],
  },
];

export const garbaEvents: GarbaEvent[] = [
  // ── FALGUNI PATHAK (14 events) ───────────────────────────────────────────────
  {
    id: "fp-01", title: "Falguni Pathak Live — Edison Navratri", artist: "Falguni Pathak", artistSlug: "falguni-pathak",
    description: "The Queen of Garba returns to Edison for an electrifying nine-night Navratri celebration. Live dhol, traditional raas circles, and the entire community under one roof.",
    venue: "NJ Convention & Exposition Center", city: "Edison", state: "NJ",
    date: "Oct 02, 2026", dateISO: "2026-10-02", time: "7:30 PM",
    category: "Garba", price: 95, priceVIP: 175, totalTickets: 4000, soldTickets: 3820,
    tags: ["Navratri", "Live Artist", "Family", "Traditional"], isNavratri: true, navratriNight: 1, featured: true,
  },
  {
    id: "fp-02", title: "Falguni Pathak — Chicago Grand Garba", artist: "Falguni Pathak", artistSlug: "falguni-pathak",
    description: "Chicago's largest Navratri celebration featuring the iconic Falguni Pathak. Three floors of garba, traditional attire encouraged, garba competition on night nine.",
    venue: "Rosemont Convention Center", city: "Chicago", state: "IL",
    date: "Oct 03, 2026", dateISO: "2026-10-03", time: "7:00 PM",
    category: "Garba", price: 85, priceVIP: 160, totalTickets: 5000, soldTickets: 4800,
    tags: ["Navratri", "Live Artist", "Competition", "Family"], isNavratri: true, navratriNight: 2,
  },
  {
    id: "fp-03", title: "Falguni Pathak — NYC Navratri Nights", artist: "Falguni Pathak", artistSlug: "falguni-pathak",
    description: "New York City's most anticipated Navratri event. Falguni Pathak performs live at Pier 36 — multiple circles, traditional and fusion floors.",
    venue: "Pier 36", city: "New York", state: "NY",
    date: "Oct 04, 2026", dateISO: "2026-10-04", time: "8:00 PM",
    category: "Garba", price: 110, priceVIP: 200, totalTickets: 3000, soldTickets: 3000,
    tags: ["Navratri", "Sold Out", "Live Artist", "NYC"], isNavratri: true, navratriNight: 3,
  },
  {
    id: "fp-04", title: "Falguni Pathak — Bay Area Navratri", artist: "Falguni Pathak", artistSlug: "falguni-pathak",
    description: "The Bay Area's premier Navratri experience. Falguni Pathak headlines the San Jose Convention Center for an unforgettable night of garba and celebration.",
    venue: "San Jose Convention Center", city: "San Jose", state: "CA",
    date: "Oct 05, 2026", dateISO: "2026-10-05", time: "7:30 PM",
    category: "Garba", price: 90, priceVIP: 170, totalTickets: 3500, soldTickets: 3220,
    tags: ["Navratri", "Live Artist", "Bay Area", "Family"], isNavratri: true, navratriNight: 4, featured: true,
  },
  {
    id: "fp-05", title: "Falguni Pathak — Houston Navratri Utsav", artist: "Falguni Pathak", artistSlug: "falguni-pathak",
    description: "Houston's Gujarati community unites for Navratri night five with the Queen of Garba. Live dhol players, professional lighting, and authentic Gujarati food stalls.",
    venue: "George R. Brown Convention Center", city: "Houston", state: "TX",
    date: "Oct 06, 2026", dateISO: "2026-10-06", time: "7:00 PM",
    category: "Garba", price: 80, priceVIP: 150, totalTickets: 4500, soldTickets: 3825,
    tags: ["Navratri", "Live Artist", "Family", "Texas"], isNavratri: true, navratriNight: 5,
  },
  {
    id: "fp-06", title: "Falguni Pathak — Atlanta Garba Mahotsav", artist: "Falguni Pathak", artistSlug: "falguni-pathak",
    description: "Atlanta's biggest Garba night featuring Falguni Pathak live. Beautifully lit mandap stage, concentric garba circles, and a celebration that goes till midnight.",
    venue: "Georgia World Congress Center", city: "Atlanta", state: "GA",
    date: "Oct 07, 2026", dateISO: "2026-10-07", time: "7:30 PM",
    category: "Garba", price: 75, priceVIP: 140, totalTickets: 3200, soldTickets: 2720,
    tags: ["Navratri", "Live Artist", "Mahotsav", "Family"], isNavratri: true, navratriNight: 6,
  },
  {
    id: "fp-07", title: "Falguni Pathak — Dallas Navratri Live", artist: "Falguni Pathak", artistSlug: "falguni-pathak",
    description: "Dallas-Fort Worth celebrates Navratri night seven with Falguni Pathak. Disco Dandiya floor, traditional garba circles, and a spectacular show.",
    venue: "Kay Bailey Hutchison Convention Center", city: "Dallas", state: "TX",
    date: "Oct 08, 2026", dateISO: "2026-10-08", time: "7:00 PM",
    category: "Garba", price: 80, priceVIP: 155, totalTickets: 3800, soldTickets: 3344,
    tags: ["Navratri", "Live Artist", "Dallas", "Dandiya"], isNavratri: true, navratriNight: 7,
  },
  {
    id: "fp-08", title: "Falguni Pathak — Los Angeles Grand Garba", artist: "Falguni Pathak", artistSlug: "falguni-pathak",
    description: "Southern California's premiere Navratri experience. Falguni Pathak live at the LA Convention Center — the biggest garba event west of Chicago.",
    venue: "Los Angeles Convention Center", city: "Los Angeles", state: "CA",
    date: "Oct 09, 2026", dateISO: "2026-10-09", time: "7:30 PM",
    category: "Garba", price: 100, priceVIP: 185, totalTickets: 4200, soldTickets: 3822,
    tags: ["Navratri", "Live Artist", "Los Angeles", "Family"], isNavratri: true, navratriNight: 8,
  },
  {
    id: "fp-09", title: "Falguni Pathak — DC Metro Navratri", artist: "Falguni Pathak", artistSlug: "falguni-pathak",
    description: "The final night of Navratri in the DC-Maryland-Virginia region with Falguni Pathak. A night-nine extravaganza with garba competition and live performances.",
    venue: "Walter E. Washington Convention Center", city: "Washington", state: "DC",
    date: "Oct 10, 2026", dateISO: "2026-10-10", time: "7:00 PM",
    category: "Garba", price: 90, priceVIP: 170, totalTickets: 3000, soldTickets: 2880,
    tags: ["Navratri", "Night Nine", "Live Artist", "Competition"], isNavratri: true, navratriNight: 9,
  },
  {
    id: "fp-10", title: "Falguni Pathak — Boston Navratri Festival", artist: "Falguni Pathak", artistSlug: "falguni-pathak",
    description: "Boston's South Asian community comes together for Falguni Pathak live. Post-Navratri celebration with traditional and modern garba styles.",
    venue: "Hynes Convention Center", city: "Boston", state: "MA",
    date: "Oct 11, 2026", dateISO: "2026-10-11", time: "7:30 PM",
    category: "Garba", price: 85, priceVIP: 160, totalTickets: 2500, soldTickets: 1875,
    tags: ["Garba", "Live Artist", "Boston", "Post-Navratri"], isNavratri: false,
  },
  {
    id: "fp-11", title: "Falguni Pathak — Phoenix Garba Night", artist: "Falguni Pathak", artistSlug: "falguni-pathak",
    description: "Arizona's biggest garba event. Falguni Pathak performs in Scottsdale for an evening that the Phoenix community has been waiting all year for.",
    venue: "Phoenix Convention Center", city: "Phoenix", state: "AZ",
    date: "Oct 12, 2026", dateISO: "2026-10-12", time: "7:00 PM",
    category: "Garba", price: 75, priceVIP: 145, totalTickets: 2800, soldTickets: 2268,
    tags: ["Garba", "Live Artist", "Arizona", "Family"], isNavratri: false,
  },
  {
    id: "fp-12", title: "Falguni Pathak — Detroit Navratri Celebration", artist: "Falguni Pathak", artistSlug: "falguni-pathak",
    description: "Metro Detroit's Gujarati diaspora celebrates with the Queen of Garba. Troy community hall transformed into a festival ground for the night.",
    venue: "Suburban Collection Showplace", city: "Novi", state: "MI",
    date: "Oct 13, 2026", dateISO: "2026-10-13", time: "7:30 PM",
    category: "Garba", price: 80, priceVIP: 150, totalTickets: 3000, soldTickets: 2310,
    tags: ["Garba", "Live Artist", "Michigan", "Family"], isNavratri: false,
  },
  {
    id: "fp-13", title: "Falguni Pathak — Denver Garba Utsav", artist: "Falguni Pathak", artistSlug: "falguni-pathak",
    description: "Pre-Navratri garba night in Denver. Falguni Pathak kicks off the season with an electrifying performance to start the festivities.",
    venue: "Colorado Convention Center", city: "Denver", state: "CO",
    date: "Sep 28, 2026", dateISO: "2026-09-28", time: "7:00 PM",
    category: "Garba", price: 70, priceVIP: 130, totalTickets: 2200, soldTickets: 1694,
    tags: ["Pre-Navratri", "Live Artist", "Denver", "Garba"], isNavratri: false,
  },
  {
    id: "fp-14", title: "Falguni Pathak — Seattle Navratri Live", artist: "Falguni Pathak", artistSlug: "falguni-pathak",
    description: "Pacific Northwest's most celebrated garba event. Falguni Pathak brings the magic of Navratri to Seattle for one spectacular night.",
    venue: "Seattle Convention Center", city: "Seattle", state: "WA",
    date: "Oct 14, 2026", dateISO: "2026-10-14", time: "7:30 PM",
    category: "Garba", price: 80, priceVIP: 150, totalTickets: 2500, soldTickets: 1750,
    tags: ["Garba", "Live Artist", "Seattle", "Pacific Northwest"], isNavratri: false,
  },

  // ── KINJAL DAVE (12 events) ──────────────────────────────────────────────────
  {
    id: "kd-01", title: "Kinjal Dave — Edison Garba Dhamaka", artist: "Kinjal Dave", artistSlug: "kinjal-dave",
    description: "Modern garba queen Kinjal Dave brings her chart-topping hits to Edison. High-energy set, fusion floor, and traditional garba circles all in one night.",
    venue: "NJ Convention & Exposition Center", city: "Edison", state: "NJ",
    date: "Oct 02, 2026", dateISO: "2026-10-02", time: "8:00 PM",
    category: "Fusion Garba", price: 55, priceVIP: 105, totalTickets: 2500, soldTickets: 2100,
    tags: ["Navratri", "Fusion", "Live Artist", "NJ"], isNavratri: true, navratriNight: 1,
  },
  {
    id: "kd-02", title: "Kinjal Dave — Chicago Navratri Night", artist: "Kinjal Dave", artistSlug: "kinjal-dave",
    description: "Chicago turns up for Kinjal Dave's high-energy Navratri performance. DJ-backed garba, folk classics, and every hit you know by heart.",
    venue: "Odeum Expo Center", city: "Villa Park", state: "IL",
    date: "Oct 04, 2026", dateISO: "2026-10-04", time: "7:30 PM",
    category: "Garba", price: 50, priceVIP: 95, totalTickets: 2000, soldTickets: 1600,
    tags: ["Navratri", "Live Artist", "Chicago", "Folk"], isNavratri: true, navratriNight: 3,
  },
  {
    id: "kd-03", title: "Kinjal Dave — Bay Area Garba Night", artist: "Kinjal Dave", artistSlug: "kinjal-dave",
    description: "Fremont's Gujarati community welcomes Kinjal Dave for a night of her biggest hits. Live backing musicians, traditional and modern garba in one space.",
    venue: "Event Center at Fremont", city: "Fremont", state: "CA",
    date: "Oct 03, 2026", dateISO: "2026-10-03", time: "7:30 PM",
    category: "Garba", price: 60, priceVIP: 110, totalTickets: 1800, soldTickets: 1548,
    tags: ["Navratri", "Live Artist", "Bay Area", "Fremont"], isNavratri: true, navratriNight: 2,
  },
  {
    id: "kd-04", title: "Kinjal Dave — Houston Dandiya Dhamaka", artist: "Kinjal Dave", artistSlug: "kinjal-dave",
    description: "Houston's dandiya celebration with Kinjal Dave. Colorful sticks, vibrant outfits, and a full night of dandiya raas with one of India's biggest folk-garba voices.",
    venue: "NRG Center", city: "Houston", state: "TX",
    date: "Oct 05, 2026", dateISO: "2026-10-05", time: "7:00 PM",
    category: "Dandiya", price: 48, priceVIP: 90, totalTickets: 3000, soldTickets: 2310,
    tags: ["Dandiya", "Live Artist", "Houston", "Texas"], isNavratri: true, navratriNight: 4,
  },
  {
    id: "kd-05", title: "Kinjal Dave — Dallas Garba Extravaganza", artist: "Kinjal Dave", artistSlug: "kinjal-dave",
    description: "Dallas celebrates Navratri night five with Kinjal Dave. An evening packed with her viral hits, live dhol, and an atmosphere that feels like Gujarat.",
    venue: "Irving Convention Center", city: "Irving", state: "TX",
    date: "Oct 06, 2026", dateISO: "2026-10-06", time: "7:30 PM",
    category: "Garba", price: 50, priceVIP: 95, totalTickets: 2200, soldTickets: 1760,
    tags: ["Navratri", "Live Artist", "Dallas", "Folk"], isNavratri: true, navratriNight: 5,
  },
  {
    id: "kd-06", title: "Kinjal Dave — Atlanta Navratri Live", artist: "Kinjal Dave", artistSlug: "kinjal-dave",
    description: "Atlanta's South Asian community turns out for Kinjal Dave's Navratri show. Fusion garba meets traditional dandiya — there's a floor for everyone.",
    venue: "Cobb Galleria Centre", city: "Atlanta", state: "GA",
    date: "Oct 07, 2026", dateISO: "2026-10-07", time: "7:30 PM",
    category: "Fusion Garba", price: 52, priceVIP: 98, totalTickets: 1800, soldTickets: 1422,
    tags: ["Navratri", "Fusion", "Live Artist", "Atlanta"], isNavratri: true, navratriNight: 6,
  },
  {
    id: "kd-07", title: "Kinjal Dave — NYC Disco Dandiya Night", artist: "Kinjal Dave", artistSlug: "kinjal-dave",
    description: "New York goes disco dandiya with Kinjal Dave. A high-production night blending her folk-garba roots with a modern NYC energy. VIP lounge available.",
    venue: "Cipriani Wall Street", city: "New York", state: "NY",
    date: "Oct 08, 2026", dateISO: "2026-10-08", time: "8:00 PM",
    category: "Disco Dandiya", price: 75, priceVIP: 140, totalTickets: 1500, soldTickets: 1290,
    tags: ["Disco Dandiya", "NYC", "Live Artist", "VIP"], isNavratri: true, navratriNight: 7, featured: true,
  },
  {
    id: "kd-08", title: "Kinjal Dave — Philadelphia Garba 2026", artist: "Kinjal Dave", artistSlug: "kinjal-dave",
    description: "Philadelphia's Gujarati community celebrates Navratri with Kinjal Dave live. Traditional garba circles, food stalls, and a night full of memories.",
    venue: "Pennsylvania Convention Center", city: "Philadelphia", state: "PA",
    date: "Oct 09, 2026", dateISO: "2026-10-09", time: "7:30 PM",
    category: "Garba", price: 52, priceVIP: 98, totalTickets: 2000, soldTickets: 1480,
    tags: ["Navratri", "Live Artist", "Philadelphia", "Traditional"], isNavratri: true, navratriNight: 8,
  },
  {
    id: "kd-09", title: "Kinjal Dave — Boston Garba Festival", artist: "Kinjal Dave", artistSlug: "kinjal-dave",
    description: "Boston's most energetic garba night. Kinjal Dave performs her biggest hits live as the city dances together for Navratri night nine.",
    venue: "Seaport World Trade Center", city: "Boston", state: "MA",
    date: "Oct 10, 2026", dateISO: "2026-10-10", time: "7:30 PM",
    category: "Garba", price: 58, priceVIP: 108, totalTickets: 1800, soldTickets: 1350,
    tags: ["Navratri", "Night Nine", "Live Artist", "Boston"], isNavratri: true, navratriNight: 9,
  },
  {
    id: "kd-10", title: "Kinjal Dave — Phoenix Navratri Live", artist: "Kinjal Dave", artistSlug: "kinjal-dave",
    description: "Scottsdale comes alive for Kinjal Dave's post-Navratri garba celebration. Her biggest folk hits and a crowd that knows every word.",
    venue: "Talking Stick Resort Arena", city: "Scottsdale", state: "AZ",
    date: "Oct 11, 2026", dateISO: "2026-10-11", time: "7:00 PM",
    category: "Garba", price: 48, priceVIP: 90, totalTickets: 2500, soldTickets: 1650,
    tags: ["Garba", "Live Artist", "Arizona", "Folk"], isNavratri: false,
  },
  {
    id: "kd-11", title: "Kinjal Dave — Orlando Garba Night", artist: "Kinjal Dave", artistSlug: "kinjal-dave",
    description: "Florida's premier garba night with Kinjal Dave. Orlando's Gujarati community joins the circle for a night packed with her chart-topping folk garba hits.",
    venue: "Orange County Convention Center", city: "Orlando", state: "FL",
    date: "Oct 12, 2026", dateISO: "2026-10-12", time: "7:30 PM",
    category: "Garba", price: 45, priceVIP: 85, totalTickets: 2000, soldTickets: 1280,
    tags: ["Garba", "Live Artist", "Florida", "Folk"], isNavratri: false,
  },
  {
    id: "kd-12", title: "Kinjal Dave — DC Navratri Utsav", artist: "Kinjal Dave", artistSlug: "kinjal-dave",
    description: "The DC metro area celebrates with Kinjal Dave. A garba utsav featuring traditional and modern styles, live musicians, and her complete hit catalog.",
    venue: "Marriott Marquis", city: "Washington", state: "DC",
    date: "Oct 13, 2026", dateISO: "2026-10-13", time: "7:30 PM",
    category: "Garba", price: 58, priceVIP: 108, totalTickets: 1500, soldTickets: 1005,
    tags: ["Garba", "Live Artist", "Washington DC", "Post-Navratri"], isNavratri: false,
  },

  // ── GEETA RABARI (11 events) ─────────────────────────────────────────────────
  {
    id: "gr-01", title: "Geeta Rabari — Jersey Folk Garba Night", artist: "Geeta Rabari", artistSlug: "geeta-rabari",
    description: "Geeta Rabari's raw, powerful folk vocals fill the room as Jersey City's Gujarati community dances in traditional concentric circles. An authentic garba experience.",
    venue: "Liberty Science Center", city: "Jersey City", state: "NJ",
    date: "Oct 02, 2026", dateISO: "2026-10-02", time: "7:30 PM",
    category: "Traditional Garba", price: 45, priceVIP: 85, totalTickets: 2000, soldTickets: 1640,
    tags: ["Folk Garba", "Traditional", "NJ", "Live Artist"], isNavratri: true, navratriNight: 1,
  },
  {
    id: "gr-02", title: "Geeta Rabari — Chicago Navratri Utsav", artist: "Geeta Rabari", artistSlug: "geeta-rabari",
    description: "Chicago's folk garba night featuring the powerhouse voice of Geeta Rabari. Traditional circular garba, live folk instruments, and an atmosphere full of culture.",
    venue: "Westin Chicago Lombard", city: "Lombard", state: "IL",
    date: "Oct 03, 2026", dateISO: "2026-10-03", time: "7:00 PM",
    category: "Traditional Garba", price: 42, priceVIP: 80, totalTickets: 1800, soldTickets: 1386,
    tags: ["Folk Garba", "Traditional", "Chicago", "Navratri"], isNavratri: true, navratriNight: 2,
  },
  {
    id: "gr-03", title: "Geeta Rabari — NYC Garba Festival", artist: "Geeta Rabari", artistSlug: "geeta-rabari",
    description: "Geeta Rabari brings Gujarat's folk tradition to New York City. A night of soulful garba vocals, live dhol, and the kind of energy only she can create.",
    venue: "Gotham Hall", city: "New York", state: "NY",
    date: "Oct 05, 2026", dateISO: "2026-10-05", time: "8:00 PM",
    category: "Traditional Garba", price: 65, priceVIP: 120, totalTickets: 1500, soldTickets: 1275,
    tags: ["Folk Garba", "Traditional", "NYC", "Cultural"], isNavratri: true, navratriNight: 4, featured: true,
  },
  {
    id: "gr-04", title: "Geeta Rabari — Houston Folk Garba Live", artist: "Geeta Rabari", artistSlug: "geeta-rabari",
    description: "Houston's garba community gathers for Geeta Rabari's folk-infused Navratri performance. Pure Gujarat tradition transplanted to Texas.",
    venue: "Stafford Centre", city: "Stafford", state: "TX",
    date: "Oct 06, 2026", dateISO: "2026-10-06", time: "7:30 PM",
    category: "Traditional Garba", price: 42, priceVIP: 80, totalTickets: 2200, soldTickets: 1628,
    tags: ["Folk Garba", "Traditional", "Houston", "Texas"], isNavratri: true, navratriNight: 5,
  },
  {
    id: "gr-05", title: "Geeta Rabari — San Jose Navratri", artist: "Geeta Rabari", artistSlug: "geeta-rabari",
    description: "Silicon Valley's Gujarati community celebrates Navratri with Geeta Rabari. Her signature folk vocals echo through the San Jose Convention Center.",
    venue: "San Jose Convention Center", city: "San Jose", state: "CA",
    date: "Oct 07, 2026", dateISO: "2026-10-07", time: "7:30 PM",
    category: "Traditional Garba", price: 55, priceVIP: 100, totalTickets: 2500, soldTickets: 2000,
    tags: ["Folk Garba", "Traditional", "Bay Area", "Navratri"], isNavratri: true, navratriNight: 6,
  },
  {
    id: "gr-06", title: "Geeta Rabari — Dallas Folk Garba Night", artist: "Geeta Rabari", artistSlug: "geeta-rabari",
    description: "Dallas gets a taste of Gujarat's folk music tradition with Geeta Rabari live. Traditional instruments, circular garba, and her iconic voice fill the hall.",
    venue: "Plano Centre", city: "Plano", state: "TX",
    date: "Oct 08, 2026", dateISO: "2026-10-08", time: "7:00 PM",
    category: "Traditional Garba", price: 40, priceVIP: 75, totalTickets: 2000, soldTickets: 1440,
    tags: ["Folk Garba", "Traditional", "Dallas", "Texas"], isNavratri: true, navratriNight: 7,
  },
  {
    id: "gr-07", title: "Geeta Rabari — Atlanta Navratri Live", artist: "Geeta Rabari", artistSlug: "geeta-rabari",
    description: "Atlanta's garba season reaches a peak with Geeta Rabari live. Traditional folk styles meet a modern stage setup — authenticity without compromise.",
    venue: "Infinite Energy Center", city: "Duluth", state: "GA",
    date: "Oct 09, 2026", dateISO: "2026-10-09", time: "7:30 PM",
    category: "Traditional Garba", price: 42, priceVIP: 80, totalTickets: 2000, soldTickets: 1480,
    tags: ["Folk Garba", "Navratri", "Atlanta", "Live Artist"], isNavratri: true, navratriNight: 8,
  },
  {
    id: "gr-08", title: "Geeta Rabari — Tampa Bay Garba", artist: "Geeta Rabari", artistSlug: "geeta-rabari",
    description: "Tampa's South Asian community celebrates Navratri with Geeta Rabari. Nine-night tradition comes to the Sunshine State.",
    venue: "Tampa Convention Center", city: "Tampa", state: "FL",
    date: "Oct 10, 2026", dateISO: "2026-10-10", time: "7:30 PM",
    category: "Traditional Garba", price: 40, priceVIP: 75, totalTickets: 1500, soldTickets: 1050,
    tags: ["Folk Garba", "Tampa", "Florida", "Navratri"], isNavratri: true, navratriNight: 9,
  },
  {
    id: "gr-09", title: "Geeta Rabari — Minneapolis Navratri", artist: "Geeta Rabari", artistSlug: "geeta-rabari",
    description: "Minnesota's Gujarati community welcomes Geeta Rabari for an authentic Navratri celebration. Folk garba circles warm up the Minnesota autumn.",
    venue: "Minneapolis Convention Center", city: "Minneapolis", state: "MN",
    date: "Oct 11, 2026", dateISO: "2026-10-11", time: "7:00 PM",
    category: "Traditional Garba", price: 38, priceVIP: 72, totalTickets: 1200, soldTickets: 792,
    tags: ["Folk Garba", "Minnesota", "Community", "Navratri"], isNavratri: false,
  },
  {
    id: "gr-10", title: "Geeta Rabari — Detroit Garba Utsav", artist: "Geeta Rabari", artistSlug: "geeta-rabari",
    description: "Metro Detroit celebrates with Geeta Rabari in Troy. A garba utsav that brings authentic Gujarat folk tradition to Michigan's largest Gujarati community.",
    venue: "Suburban Collection Showplace", city: "Novi", state: "MI",
    date: "Oct 12, 2026", dateISO: "2026-10-12", time: "7:30 PM",
    category: "Traditional Garba", price: 40, priceVIP: 76, totalTickets: 1800, soldTickets: 1188,
    tags: ["Folk Garba", "Michigan", "Traditional", "Community"], isNavratri: false,
  },
  {
    id: "gr-11", title: "Geeta Rabari — Columbus Navratri Live", artist: "Geeta Rabari", artistSlug: "geeta-rabari",
    description: "Ohio's Gujarati diaspora gathers for Geeta Rabari in Columbus. Traditional folk garba with live instruments for a night of pure cultural celebration.",
    venue: "Greater Columbus Convention Center", city: "Columbus", state: "OH",
    date: "Oct 13, 2026", dateISO: "2026-10-13", time: "7:00 PM",
    category: "Traditional Garba", price: 38, priceVIP: 72, totalTickets: 1200, soldTickets: 756,
    tags: ["Folk Garba", "Ohio", "Traditional", "Community"], isNavratri: false,
  },

  // ── AISHWARYA MAJMUDAR (10 events) ───────────────────────────────────────────
  {
    id: "am-01", title: "Aishwarya Majmudar — Edison Classical Garba", artist: "Aishwarya Majmudar", artistSlug: "aishwarya-majmudar",
    description: "Aishwarya Majmudar's classically trained voice elevates Navratri to a cultural event. Traditional raas and garba in a beautifully curated setting.",
    venue: "Pines Manor", city: "Edison", state: "NJ",
    date: "Oct 02, 2026", dateISO: "2026-10-02", time: "7:30 PM",
    category: "Traditional Garba", price: 50, priceVIP: 95, totalTickets: 1500, soldTickets: 1215,
    tags: ["Classical", "Traditional", "NJ", "Cultural"], isNavratri: true, navratriNight: 1,
  },
  {
    id: "am-02", title: "Aishwarya Majmudar — Chicago Navratri", artist: "Aishwarya Majmudar", artistSlug: "aishwarya-majmudar",
    description: "Chicago's cultural Navratri evening featuring Aishwarya Majmudar. Classical compositions meet traditional garba circles in an atmosphere of pure festivity.",
    venue: "Sheraton Grand Chicago", city: "Chicago", state: "IL",
    date: "Oct 04, 2026", dateISO: "2026-10-04", time: "7:00 PM",
    category: "Garba", price: 48, priceVIP: 90, totalTickets: 1200, soldTickets: 912,
    tags: ["Classical", "Traditional", "Chicago", "Cultural"], isNavratri: true, navratriNight: 3,
  },
  {
    id: "am-03", title: "Aishwarya Majmudar — NYC Garba Night", artist: "Aishwarya Majmudar", artistSlug: "aishwarya-majmudar",
    description: "A refined and soulful Navratri evening in New York with Aishwarya Majmudar. Her SAI-NIMBUS-spanning vocal range creates garba moments you don't forget.",
    venue: "The Plaza Hotel", city: "New York", state: "NY",
    date: "Oct 05, 2026", dateISO: "2026-10-05", time: "8:00 PM",
    category: "Garba", price: 80, priceVIP: 150, totalTickets: 800, soldTickets: 720,
    tags: ["Classical", "NYC", "Cultural", "Navratri"], isNavratri: true, navratriNight: 4,
  },
  {
    id: "am-04", title: "Aishwarya Majmudar — Bay Area Navratri", artist: "Aishwarya Majmudar", artistSlug: "aishwarya-majmudar",
    description: "San Jose's Navratri night six with Aishwarya Majmudar. A classical garba performance that honors the tradition while filling an arena with celebration.",
    venue: "City National Civic", city: "San Jose", state: "CA",
    date: "Oct 06, 2026", dateISO: "2026-10-06", time: "7:30 PM",
    category: "Garba", price: 58, priceVIP: 110, totalTickets: 1800, soldTickets: 1404,
    tags: ["Classical", "Bay Area", "Cultural", "Navratri"], isNavratri: true, navratriNight: 5,
  },
  {
    id: "am-05", title: "Aishwarya Majmudar — Houston Garba Utsav", artist: "Aishwarya Majmudar", artistSlug: "aishwarya-majmudar",
    description: "Houston celebrates Navratri with Aishwarya Majmudar's powerful classical garba vocals. Traditional attire encouraged. Beginner circles available.",
    venue: "Sugar Land Smart Financial Centre", city: "Sugar Land", state: "TX",
    date: "Oct 07, 2026", dateISO: "2026-10-07", time: "7:30 PM",
    category: "Traditional Garba", price: 48, priceVIP: 90, totalTickets: 2000, soldTickets: 1440,
    tags: ["Classical", "Houston", "Traditional", "Navratri"], isNavratri: true, navratriNight: 6,
  },
  {
    id: "am-06", title: "Aishwarya Majmudar — Atlanta Navratri Live", artist: "Aishwarya Majmudar", artistSlug: "aishwarya-majmudar",
    description: "Atlanta's Navratri night seven features Aishwarya Majmudar. Classical garba meets folk roots — a performance that encapsulates the season.",
    venue: "Cobb Energy Performing Arts Centre", city: "Atlanta", state: "GA",
    date: "Oct 08, 2026", dateISO: "2026-10-08", time: "7:30 PM",
    category: "Garba", price: 50, priceVIP: 95, totalTickets: 1500, soldTickets: 1050,
    tags: ["Classical", "Atlanta", "Cultural", "Navratri"], isNavratri: true, navratriNight: 7,
  },
  {
    id: "am-07", title: "Aishwarya Majmudar — Dallas Garba Festival", artist: "Aishwarya Majmudar", artistSlug: "aishwarya-majmudar",
    description: "Dallas-Fort Worth celebrates with Aishwarya Majmudar live. Night eight of Navratri with classical raas circles and a closing ceremony to remember.",
    venue: "Plano Event Center", city: "Plano", state: "TX",
    date: "Oct 09, 2026", dateISO: "2026-10-09", time: "7:00 PM",
    category: "Garba", price: 48, priceVIP: 90, totalTickets: 1800, soldTickets: 1188,
    tags: ["Classical", "Dallas", "Traditional", "Navratri"], isNavratri: true, navratriNight: 8,
  },
  {
    id: "am-08", title: "Aishwarya Majmudar — DC Navratri Night", artist: "Aishwarya Majmudar", artistSlug: "aishwarya-majmudar",
    description: "Washington DC's Navratri finale with Aishwarya Majmudar. Night nine celebration — the grand closing of the season with a classical garba sendoff.",
    venue: "MGM National Harbor", city: "Oxon Hill", state: "MD",
    date: "Oct 10, 2026", dateISO: "2026-10-10", time: "7:30 PM",
    category: "Garba", price: 58, priceVIP: 108, totalTickets: 1500, soldTickets: 1200,
    tags: ["Classical", "DC", "Night Nine", "Navratri"], isNavratri: true, navratriNight: 9,
  },
  {
    id: "am-09", title: "Aishwarya Majmudar — Charlotte Garba", artist: "Aishwarya Majmudar", artistSlug: "aishwarya-majmudar",
    description: "Charlotte's growing Gujarati community welcomes Aishwarya Majmudar. Post-Navratri garba with a classical performance in Charlotte's largest event space.",
    venue: "Charlotte Convention Center", city: "Charlotte", state: "NC",
    date: "Oct 11, 2026", dateISO: "2026-10-11", time: "7:30 PM",
    category: "Garba", price: 42, priceVIP: 80, totalTickets: 1200, soldTickets: 756,
    tags: ["Classical", "Charlotte", "Community", "Post-Navratri"], isNavratri: false,
  },
  {
    id: "am-10", title: "Aishwarya Majmudar — Miami Navratri Live", artist: "Aishwarya Majmudar", artistSlug: "aishwarya-majmudar",
    description: "South Florida's garba celebration with Aishwarya Majmudar. Miami's vibrant Gujarati community dances to her timeless classical garba compositions.",
    venue: "Mana Wynwood", city: "Miami", state: "FL",
    date: "Oct 12, 2026", dateISO: "2026-10-12", time: "8:00 PM",
    category: "Garba", price: 58, priceVIP: 110, totalTickets: 1500, soldTickets: 930,
    tags: ["Classical", "Miami", "Florida", "Community"], isNavratri: false,
  },

  // ── HEMANT CHAUHAN (10 events) ───────────────────────────────────────────────
  {
    id: "hc-01", title: "Hemant Chauhan — Traditional Garba Edison", artist: "Hemant Chauhan", artistSlug: "hemant-chauhan",
    description: "Hemant Chauhan, the maestro of traditional Gujarati garba, opens Navratri in Edison with a pure, uncompromising folk garba night. No DJ, just culture.",
    venue: "Gujarati Samaj of NJ", city: "Edison", state: "NJ",
    date: "Oct 03, 2026", dateISO: "2026-10-03", time: "7:00 PM",
    category: "Traditional Garba", price: 40, priceVIP: 75, totalTickets: 1500, soldTickets: 1200,
    tags: ["Traditional", "Folk", "NJ", "Cultural"], isNavratri: true, navratriNight: 2,
  },
  {
    id: "hc-02", title: "Hemant Chauhan — Chicago Grand Garba", artist: "Hemant Chauhan", artistSlug: "hemant-chauhan",
    description: "Chicago's traditionalist garba community comes together for Hemant Chauhan. Authentic Gujarati folk garba with live instruments and no compromise on tradition.",
    venue: "Drury Lane Theatre", city: "Oak Brook Terrace", state: "IL",
    date: "Oct 04, 2026", dateISO: "2026-10-04", time: "7:00 PM",
    category: "Traditional Garba", price: 38, priceVIP: 70, totalTickets: 1200, soldTickets: 912,
    tags: ["Traditional", "Folk", "Chicago", "Navratri"], isNavratri: true, navratriNight: 3,
  },
  {
    id: "hc-03", title: "Hemant Chauhan — NYC Navratri Festival", artist: "Hemant Chauhan", artistSlug: "hemant-chauhan",
    description: "New York's traditional garba night with Hemant Chauhan. A return to roots — folk instruments, concentric circles, and the songs your grandparents danced to.",
    venue: "Queens County Farm Museum", city: "Floral Park", state: "NY",
    date: "Oct 05, 2026", dateISO: "2026-10-05", time: "7:30 PM",
    category: "Traditional Garba", price: 48, priceVIP: 90, totalTickets: 1000, soldTickets: 780,
    tags: ["Traditional", "Folk", "NYC", "Cultural"], isNavratri: true, navratriNight: 4,
  },
  {
    id: "hc-04", title: "Hemant Chauhan — Bay Area Folk Garba", artist: "Hemant Chauhan", artistSlug: "hemant-chauhan",
    description: "Fremont's traditional garba night with Hemant Chauhan. An evening dedicated to preserving and celebrating authentic Gujarati folk garba for all generations.",
    venue: "Fremont Community Center", city: "Fremont", state: "CA",
    date: "Oct 06, 2026", dateISO: "2026-10-06", time: "7:00 PM",
    category: "Traditional Garba", price: 40, priceVIP: 75, totalTickets: 1200, soldTickets: 888,
    tags: ["Traditional", "Folk", "Bay Area", "Cultural"], isNavratri: true, navratriNight: 5,
  },
  {
    id: "hc-05", title: "Hemant Chauhan — Houston Traditional Garba", artist: "Hemant Chauhan", artistSlug: "hemant-chauhan",
    description: "Houston celebrates its traditional garba heritage with Hemant Chauhan. Folk garba in its purest form — the way it was meant to be experienced.",
    venue: "Lone Star Convention Center", city: "Conroe", state: "TX",
    date: "Oct 07, 2026", dateISO: "2026-10-07", time: "7:30 PM",
    category: "Traditional Garba", price: 38, priceVIP: 70, totalTickets: 1500, soldTickets: 1050,
    tags: ["Traditional", "Folk", "Houston", "Cultural"], isNavratri: true, navratriNight: 6,
  },
  {
    id: "hc-06", title: "Hemant Chauhan — Dallas Navratri Night", artist: "Hemant Chauhan", artistSlug: "hemant-chauhan",
    description: "Dallas honors Navratri's folk roots with Hemant Chauhan. Seven circles, live folk instruments, and a celebration that feels like a village in Gujarat.",
    venue: "Allen Event Center", city: "Allen", state: "TX",
    date: "Oct 08, 2026", dateISO: "2026-10-08", time: "7:00 PM",
    category: "Traditional Garba", price: 38, priceVIP: 70, totalTickets: 1500, soldTickets: 1020,
    tags: ["Traditional", "Folk", "Dallas", "Navratri"], isNavratri: true, navratriNight: 7,
  },
  {
    id: "hc-07", title: "Hemant Chauhan — Boston Garba Utsav", artist: "Hemant Chauhan", artistSlug: "hemant-chauhan",
    description: "Boston's traditional garba night with Hemant Chauhan. An evening of authentic folk garba, live dhol and tabla, and the songs that have defined Navratri for decades.",
    venue: "Sheraton Boston Hotel", city: "Boston", state: "MA",
    date: "Oct 09, 2026", dateISO: "2026-10-09", time: "7:30 PM",
    category: "Traditional Garba", price: 45, priceVIP: 84, totalTickets: 1200, soldTickets: 876,
    tags: ["Traditional", "Folk", "Boston", "Cultural"], isNavratri: true, navratriNight: 8,
  },
  {
    id: "hc-08", title: "Hemant Chauhan — Philadelphia Navratri", artist: "Hemant Chauhan", artistSlug: "hemant-chauhan",
    description: "Philadelphia honors Navratri's nine-night tradition with Hemant Chauhan live. Night nine — the closing celebration of the season in true folk style.",
    venue: "Sheraton Philadelphia Downtown", city: "Philadelphia", state: "PA",
    date: "Oct 10, 2026", dateISO: "2026-10-10", time: "7:30 PM",
    category: "Traditional Garba", price: 42, priceVIP: 78, totalTickets: 1000, soldTickets: 680,
    tags: ["Traditional", "Night Nine", "Philadelphia", "Cultural"], isNavratri: true, navratriNight: 9,
  },
  {
    id: "hc-09", title: "Hemant Chauhan — Phoenix Traditional Garba", artist: "Hemant Chauhan", artistSlug: "hemant-chauhan",
    description: "Arizona's traditional garba community gathers for Hemant Chauhan in Phoenix. Post-season folk garba for those who want the authentic experience year-round.",
    venue: "Phoenix Convention Center", city: "Phoenix", state: "AZ",
    date: "Oct 11, 2026", dateISO: "2026-10-11", time: "7:00 PM",
    category: "Traditional Garba", price: 38, priceVIP: 70, totalTickets: 1500, soldTickets: 930,
    tags: ["Traditional", "Folk", "Arizona", "Community"], isNavratri: false,
  },
  {
    id: "hc-10", title: "Hemant Chauhan — Atlanta Garba Mahotsav", artist: "Hemant Chauhan", artistSlug: "hemant-chauhan",
    description: "Atlanta's garba mahotsav features Hemant Chauhan in a two-hour traditional garba set. Pure folk tradition, no shortcuts, just authentic culture.",
    venue: "Atlanta Marriott Marquis", city: "Atlanta", state: "GA",
    date: "Oct 12, 2026", dateISO: "2026-10-12", time: "7:30 PM",
    category: "Traditional Garba", price: 40, priceVIP: 75, totalTickets: 1500, soldTickets: 960,
    tags: ["Traditional", "Folk", "Atlanta", "Mahotsav"], isNavratri: false,
  },

  // ── ATUL PUROHIT (10 events) ─────────────────────────────────────────────────
  {
    id: "ap-01", title: "Atul Purohit — Edison Garba Nite", artist: "Atul Purohit", artistSlug: "atul-purohit",
    description: "Atul Purohit, the garba legend, opens Navratri in Edison with his signature high-energy folk garba. Thousands of circles, one unforgettable night.",
    venue: "Raritan Center", city: "Edison", state: "NJ",
    date: "Oct 02, 2026", dateISO: "2026-10-02", time: "7:30 PM",
    category: "Garba", price: 50, priceVIP: 95, totalTickets: 2500, soldTickets: 2000,
    tags: ["Garba", "Legend", "NJ", "Navratri"], isNavratri: true, navratriNight: 1,
  },
  {
    id: "ap-02", title: "Atul Purohit — Chicago Navratri Live", artist: "Atul Purohit", artistSlug: "atul-purohit",
    description: "The legend returns to Chicago for night three of Navratri. Atul Purohit's timeless garba repertoire fills the ballroom as thousands dance in circles.",
    venue: "Loews Chicago O'Hare", city: "Rosemont", state: "IL",
    date: "Oct 04, 2026", dateISO: "2026-10-04", time: "7:00 PM",
    category: "Garba", price: 45, priceVIP: 85, totalTickets: 2200, soldTickets: 1716,
    tags: ["Garba", "Legend", "Chicago", "Navratri"], isNavratri: true, navratriNight: 3,
  },
  {
    id: "ap-03", title: "Atul Purohit — NYC Garba Utsav", artist: "Atul Purohit", artistSlug: "atul-purohit",
    description: "New York's garba utsav with Atul Purohit live. His classic garba compositions ring out across the city as the community dances together for night four.",
    venue: "Terminal 5", city: "New York", state: "NY",
    date: "Oct 05, 2026", dateISO: "2026-10-05", time: "8:00 PM",
    category: "Garba", price: 65, priceVIP: 120, totalTickets: 1500, soldTickets: 1260,
    tags: ["Garba", "Legend", "NYC", "Cultural"], isNavratri: true, navratriNight: 4, featured: true,
  },
  {
    id: "ap-04", title: "Atul Purohit — Bay Area Garba Festival", artist: "Atul Purohit", artistSlug: "atul-purohit",
    description: "San Jose celebrates Navratri night five with the garba legend Atul Purohit. Over a decade of Bay Area Navratri history, and this one promises to top them all.",
    venue: "SAP Center", city: "San Jose", state: "CA",
    date: "Oct 06, 2026", dateISO: "2026-10-06", time: "7:30 PM",
    category: "Garba", price: 60, priceVIP: 110, totalTickets: 3000, soldTickets: 2520,
    tags: ["Garba", "Legend", "Bay Area", "Navratri"], isNavratri: true, navratriNight: 5,
  },
  {
    id: "ap-05", title: "Atul Purohit — Houston Navratri Night", artist: "Atul Purohit", artistSlug: "atul-purohit",
    description: "Houston comes alive for Atul Purohit on Navratri night six. The garba legend brings his complete repertoire — expect circles that don't stop till midnight.",
    venue: "Smart Financial Centre at Sugar Land", city: "Sugar Land", state: "TX",
    date: "Oct 07, 2026", dateISO: "2026-10-07", time: "7:00 PM",
    category: "Garba", price: 50, priceVIP: 95, totalTickets: 2500, soldTickets: 1950,
    tags: ["Garba", "Legend", "Houston", "Navratri"], isNavratri: true, navratriNight: 6,
  },
  {
    id: "ap-06", title: "Atul Purohit — Dallas Garba Live", artist: "Atul Purohit", artistSlug: "atul-purohit",
    description: "Dallas honors Navratri night seven with Atul Purohit's classic garba. Three hours of non-stop garba with the legend himself leading every circle.",
    venue: "Frontiers of Flight Museum", city: "Dallas", state: "TX",
    date: "Oct 08, 2026", dateISO: "2026-10-08", time: "7:30 PM",
    category: "Garba", price: 50, priceVIP: 95, totalTickets: 2000, soldTickets: 1580,
    tags: ["Garba", "Legend", "Dallas", "Navratri"], isNavratri: true, navratriNight: 7,
  },
  {
    id: "ap-07", title: "Atul Purohit — Atlanta Navratri Festival", artist: "Atul Purohit", artistSlug: "atul-purohit",
    description: "Atlanta's Navratri night eight — Atul Purohit performs his most beloved garba compositions for the penultimate night of the season.",
    venue: "Gas South Convention Center", city: "Duluth", state: "GA",
    date: "Oct 09, 2026", dateISO: "2026-10-09", time: "7:30 PM",
    category: "Garba", price: 50, priceVIP: 92, totalTickets: 2000, soldTickets: 1520,
    tags: ["Garba", "Legend", "Atlanta", "Navratri"], isNavratri: true, navratriNight: 8,
  },
  {
    id: "ap-08", title: "Atul Purohit — DC Garba Utsav", artist: "Atul Purohit", artistSlug: "atul-purohit",
    description: "Washington DC closes Navratri with Atul Purohit live. Night nine — the final night of the season, the most emotional circle of the year.",
    venue: "Gaylord National Resort", city: "Oxon Hill", state: "MD",
    date: "Oct 10, 2026", dateISO: "2026-10-10", time: "7:30 PM",
    category: "Garba", price: 58, priceVIP: 108, totalTickets: 2000, soldTickets: 1680,
    tags: ["Garba", "Night Nine", "DC", "Legend"], isNavratri: true, navratriNight: 9,
  },
  {
    id: "ap-09", title: "Atul Purohit — Detroit Navratri Night", artist: "Atul Purohit", artistSlug: "atul-purohit",
    description: "Metro Detroit's post-Navratri celebration with Atul Purohit. Michigan's Gujarati community gathers for one more round of the season's best garba.",
    venue: "Detroit Marriott Renaissance Center", city: "Detroit", state: "MI",
    date: "Oct 11, 2026", dateISO: "2026-10-11", time: "7:00 PM",
    category: "Garba", price: 45, priceVIP: 85, totalTickets: 1500, soldTickets: 975,
    tags: ["Garba", "Legend", "Michigan", "Post-Navratri"], isNavratri: false,
  },
  {
    id: "ap-10", title: "Atul Purohit — Denver Garba Extravaganza", artist: "Atul Purohit", artistSlug: "atul-purohit",
    description: "Denver's garba extravaganza features Atul Purohit in a full-length performance. Colorado's Gujarati community celebrates in style at the Convention Center.",
    venue: "Colorado Convention Center", city: "Denver", state: "CO",
    date: "Oct 12, 2026", dateISO: "2026-10-12", time: "7:30 PM",
    category: "Garba", price: 45, priceVIP: 85, totalTickets: 1500, soldTickets: 945,
    tags: ["Garba", "Legend", "Denver", "Colorado"], isNavratri: false,
  },

  // ── OSMAN MIR (9 events) ─────────────────────────────────────────────────────
  {
    id: "om-01", title: "Osman Mir — Sufi Garba Night Edison", artist: "Osman Mir", artistSlug: "osman-mir",
    description: "Osman Mir's soulful sufi-meets-garba performance is an experience unlike any other. The devotion in his voice turns every garba circle into a meditative journey.",
    venue: "Doubletree by Hilton", city: "Edison", state: "NJ",
    date: "Oct 03, 2026", dateISO: "2026-10-03", time: "7:30 PM",
    category: "Sufi Garba", price: 45, priceVIP: 85, totalTickets: 1200, soldTickets: 924,
    tags: ["Sufi", "Folk", "NJ", "Cultural"], isNavratri: true, navratriNight: 2,
  },
  {
    id: "om-02", title: "Osman Mir — Chicago Sufi Garba", artist: "Osman Mir", artistSlug: "osman-mir",
    description: "Chicago's sufi garba night with Osman Mir. His unique blend of devotional music and folk garba creates an atmosphere of spiritual celebration.",
    venue: "Hotel Arista", city: "Naperville", state: "IL",
    date: "Oct 04, 2026", dateISO: "2026-10-04", time: "7:00 PM",
    category: "Sufi Garba", price: 40, priceVIP: 75, totalTickets: 1000, soldTickets: 720,
    tags: ["Sufi", "Folk", "Chicago", "Spiritual"], isNavratri: true, navratriNight: 3,
  },
  {
    id: "om-03", title: "Osman Mir — NYC Folk & Sufi Night", artist: "Osman Mir", artistSlug: "osman-mir",
    description: "New York's most spiritual Navratri evening. Osman Mir performs folk and sufi garba at an intimate venue — a night of music, devotion, and dance.",
    venue: "The Great Hall at Cooper Union", city: "New York", state: "NY",
    date: "Oct 05, 2026", dateISO: "2026-10-05", time: "8:00 PM",
    category: "Sufi Garba", price: 60, priceVIP: 110, totalTickets: 800, soldTickets: 648,
    tags: ["Sufi", "Folk", "NYC", "Spiritual"], isNavratri: true, navratriNight: 4, featured: true,
  },
  {
    id: "om-04", title: "Osman Mir — Bay Area Sufi Garba", artist: "Osman Mir", artistSlug: "osman-mir",
    description: "San Jose's sufi garba evening with Osman Mir. A devotional journey through Gujarat's folk and sufi traditions that leaves the audience transformed.",
    venue: "California Theatre", city: "San Jose", state: "CA",
    date: "Oct 06, 2026", dateISO: "2026-10-06", time: "7:30 PM",
    category: "Sufi Garba", price: 52, priceVIP: 98, totalTickets: 1200, soldTickets: 912,
    tags: ["Sufi", "Folk", "Bay Area", "Spiritual"], isNavratri: true, navratriNight: 5,
  },
  {
    id: "om-05", title: "Osman Mir — Houston Navratri Night", artist: "Osman Mir", artistSlug: "osman-mir",
    description: "Houston's sufi garba experience with Osman Mir. A night of folk garba with a devotional edge — equal parts celebration and spiritual awakening.",
    venue: "Wortham Theater Center", city: "Houston", state: "TX",
    date: "Oct 07, 2026", dateISO: "2026-10-07", time: "7:30 PM",
    category: "Sufi Garba", price: 45, priceVIP: 85, totalTickets: 1500, soldTickets: 1050,
    tags: ["Sufi", "Folk", "Houston", "Spiritual"], isNavratri: true, navratriNight: 6,
  },
  {
    id: "om-06", title: "Osman Mir — Dallas Sufi Garba Live", artist: "Osman Mir", artistSlug: "osman-mir",
    description: "Dallas celebrates Navratri night seven with Osman Mir's devotional garba. Folk, sufi, and traditional — an evening that bridges all of Gujarat's musical traditions.",
    venue: "Eisemann Center", city: "Richardson", state: "TX",
    date: "Oct 08, 2026", dateISO: "2026-10-08", time: "7:00 PM",
    category: "Sufi Garba", price: 42, priceVIP: 80, totalTickets: 1200, soldTickets: 840,
    tags: ["Sufi", "Folk", "Dallas", "Cultural"], isNavratri: true, navratriNight: 7,
  },
  {
    id: "om-07", title: "Osman Mir — Atlanta Folk Garba", artist: "Osman Mir", artistSlug: "osman-mir",
    description: "Atlanta's folk garba night with Osman Mir. His performances carry the weight of centuries of Gujarati musical tradition — a rare cultural event.",
    venue: "Atlanta Symphony Hall", city: "Atlanta", state: "GA",
    date: "Oct 09, 2026", dateISO: "2026-10-09", time: "7:30 PM",
    category: "Sufi Garba", price: 45, priceVIP: 85, totalTickets: 1000, soldTickets: 720,
    tags: ["Sufi", "Folk", "Atlanta", "Cultural"], isNavratri: true, navratriNight: 8,
  },
  {
    id: "om-08", title: "Osman Mir — Boston Navratri Night", artist: "Osman Mir", artistSlug: "osman-mir",
    description: "Boston's sufi garba night with Osman Mir. A night-nine closing ceremony unlike any other — devotional, folk, and deeply moving.",
    venue: "Berklee Performance Center", city: "Boston", state: "MA",
    date: "Oct 10, 2026", dateISO: "2026-10-10", time: "7:30 PM",
    category: "Sufi Garba", price: 52, priceVIP: 98, totalTickets: 1000, soldTickets: 700,
    tags: ["Sufi", "Night Nine", "Boston", "Spiritual"], isNavratri: true, navratriNight: 9,
  },
  {
    id: "om-09", title: "Osman Mir — Seattle Garba Festival", artist: "Osman Mir", artistSlug: "osman-mir",
    description: "Seattle's Pacific Northwest garba festival with Osman Mir. A post-Navratri sufi garba experience for those who never want the season to end.",
    venue: "Benaroya Hall", city: "Seattle", state: "WA",
    date: "Oct 11, 2026", dateISO: "2026-10-11", time: "7:30 PM",
    category: "Sufi Garba", price: 48, priceVIP: 90, totalTickets: 1000, soldTickets: 640,
    tags: ["Sufi", "Folk", "Seattle", "Post-Navratri"], isNavratri: false,
  },

  // ── REKHA TRIVEDI (9 events) ─────────────────────────────────────────────────
  {
    id: "rt-01", title: "Rekha Trivedi — Edison Traditional Garba", artist: "Rekha Trivedi", artistSlug: "rekha-trivedi",
    description: "Rekha Trivedi brings the authentic folk garba tradition of rural Gujarat to Edison. Her powerful voice and traditional repertoire honor the roots of Navratri.",
    venue: "Pines Manor", city: "Edison", state: "NJ",
    date: "Oct 02, 2026", dateISO: "2026-10-02", time: "7:00 PM",
    category: "Traditional Garba", price: 40, priceVIP: 75, totalTickets: 1500, soldTickets: 1200,
    tags: ["Traditional", "Folk", "NJ", "Cultural"], isNavratri: true, navratriNight: 1,
  },
  {
    id: "rt-02", title: "Rekha Trivedi — Chicago Navratri Night", artist: "Rekha Trivedi", artistSlug: "rekha-trivedi",
    description: "Chicago's traditional garba night three with Rekha Trivedi. Authentic folk garba, no production gimmicks — just her voice, the dhol, and the circle.",
    venue: "Westin Chicago Lombard", city: "Lombard", state: "IL",
    date: "Oct 04, 2026", dateISO: "2026-10-04", time: "7:00 PM",
    category: "Traditional Garba", price: 38, priceVIP: 70, totalTickets: 1200, soldTickets: 888,
    tags: ["Traditional", "Folk", "Chicago", "Cultural"], isNavratri: true, navratriNight: 3,
  },
  {
    id: "rt-03", title: "Rekha Trivedi — NYC Garba Festival", artist: "Rekha Trivedi", artistSlug: "rekha-trivedi",
    description: "New York's folk garba night four with Rekha Trivedi. Her voice fills the venue with the spirit of Gujarat — a night that honors the living tradition.",
    venue: "City Winery NYC", city: "New York", state: "NY",
    date: "Oct 05, 2026", dateISO: "2026-10-05", time: "8:00 PM",
    category: "Traditional Garba", price: 58, priceVIP: 108, totalTickets: 1000, soldTickets: 800,
    tags: ["Traditional", "Folk", "NYC", "Cultural"], isNavratri: true, navratriNight: 4,
  },
  {
    id: "rt-04", title: "Rekha Trivedi — Bay Area Navratri Live", artist: "Rekha Trivedi", artistSlug: "rekha-trivedi",
    description: "Fremont's Navratri night five with Rekha Trivedi. Traditional garba circles under one roof — the kind of night that connects generations.",
    venue: "Event Center at Fremont", city: "Fremont", state: "CA",
    date: "Oct 06, 2026", dateISO: "2026-10-06", time: "7:30 PM",
    category: "Traditional Garba", price: 45, priceVIP: 84, totalTickets: 1500, soldTickets: 1110,
    tags: ["Traditional", "Folk", "Bay Area", "Navratri"], isNavratri: true, navratriNight: 5,
  },
  {
    id: "rt-05", title: "Rekha Trivedi — Houston Traditional Garba", artist: "Rekha Trivedi", artistSlug: "rekha-trivedi",
    description: "Houston's traditional garba night with Rekha Trivedi. Her folk garba style — steeped in Gujarat's village traditions — is rare to experience live in the USA.",
    venue: "Stafford Centre", city: "Stafford", state: "TX",
    date: "Oct 07, 2026", dateISO: "2026-10-07", time: "7:30 PM",
    category: "Traditional Garba", price: 38, priceVIP: 70, totalTickets: 1500, soldTickets: 1050,
    tags: ["Traditional", "Folk", "Houston", "Cultural"], isNavratri: true, navratriNight: 6,
  },
  {
    id: "rt-06", title: "Rekha Trivedi — Dallas Folk Garba", artist: "Rekha Trivedi", artistSlug: "rekha-trivedi",
    description: "Dallas celebrates Navratri night seven with Rekha Trivedi's pure folk garba. An evening dedicated to authenticity — dress traditionally, dance traditionally.",
    venue: "Plano Centre", city: "Plano", state: "TX",
    date: "Oct 08, 2026", dateISO: "2026-10-08", time: "7:00 PM",
    category: "Traditional Garba", price: 38, priceVIP: 70, totalTickets: 1200, soldTickets: 828,
    tags: ["Traditional", "Folk", "Dallas", "Cultural"], isNavratri: true, navratriNight: 7,
  },
  {
    id: "rt-07", title: "Rekha Trivedi — Atlanta Navratri Utsav", artist: "Rekha Trivedi", artistSlug: "rekha-trivedi",
    description: "Atlanta celebrates Navratri night eight with Rekha Trivedi. Her garba utsav is a cultural event as much as a celebration — history and festivity in one evening.",
    venue: "Atlanta Marriott Marquis", city: "Atlanta", state: "GA",
    date: "Oct 09, 2026", dateISO: "2026-10-09", time: "7:30 PM",
    category: "Traditional Garba", price: 40, priceVIP: 75, totalTickets: 1200, soldTickets: 840,
    tags: ["Traditional", "Folk", "Atlanta", "Cultural"], isNavratri: true, navratriNight: 8,
  },
  {
    id: "rt-08", title: "Rekha Trivedi — Orlando Garba Night", artist: "Rekha Trivedi", artistSlug: "rekha-trivedi",
    description: "Florida celebrates the final night of Navratri with Rekha Trivedi in Orlando. Night nine — her most emotionally charged performance of the season.",
    venue: "Orlando World Center Marriott", city: "Orlando", state: "FL",
    date: "Oct 10, 2026", dateISO: "2026-10-10", time: "7:30 PM",
    category: "Traditional Garba", price: 38, priceVIP: 70, totalTickets: 1200, soldTickets: 792,
    tags: ["Traditional", "Night Nine", "Florida", "Cultural"], isNavratri: true, navratriNight: 9,
  },
  {
    id: "rt-09", title: "Rekha Trivedi — Cincinnati Navratri Live", artist: "Rekha Trivedi", artistSlug: "rekha-trivedi",
    description: "Ohio's Navratri garba with Rekha Trivedi in Cincinnati. Post-season folk garba for a community that never gets enough of the tradition.",
    venue: "Duke Energy Convention Center", city: "Cincinnati", state: "OH",
    date: "Oct 11, 2026", dateISO: "2026-10-11", time: "7:00 PM",
    category: "Traditional Garba", price: 36, priceVIP: 68, totalTickets: 1000, soldTickets: 620,
    tags: ["Traditional", "Folk", "Ohio", "Community"], isNavratri: false,
  },

  // ── SACHIN-JIGAR (8 events) ──────────────────────────────────────────────────
  {
    id: "sj-01", title: "Sachin-Jigar — Bollywood Garba Edison", artist: "Sachin-Jigar", artistSlug: "sachin-jigar",
    description: "Bollywood composers turned garba stars — Sachin-Jigar bring their chart-topping hits and Navratri energy to Edison. A fusion night that sets the season on fire.",
    venue: "NJ Convention & Exposition Center", city: "Edison", state: "NJ",
    date: "Oct 03, 2026", dateISO: "2026-10-03", time: "8:00 PM",
    category: "Fusion Garba", price: 65, priceVIP: 125, totalTickets: 2500, soldTickets: 2125,
    tags: ["Bollywood", "Fusion", "NJ", "Live Artists"], isNavratri: true, navratriNight: 2, featured: true,
  },
  {
    id: "sj-02", title: "Sachin-Jigar — Chicago Fusion Garba", artist: "Sachin-Jigar", artistSlug: "sachin-jigar",
    description: "Chicago's most buzzed-about Navratri night — Sachin-Jigar bring Bollywood's biggest garba hits to the Midwest. High production, high energy, all night.",
    venue: "Rosemont Theatre", city: "Rosemont", state: "IL",
    date: "Oct 04, 2026", dateISO: "2026-10-04", time: "7:30 PM",
    category: "Fusion Garba", price: 62, priceVIP: 115, totalTickets: 2000, soldTickets: 1740,
    tags: ["Bollywood", "Fusion", "Chicago", "Navratri"], isNavratri: true, navratriNight: 3,
  },
  {
    id: "sj-03", title: "Sachin-Jigar — NYC Bollywood Garba", artist: "Sachin-Jigar", artistSlug: "sachin-jigar",
    description: "New York City turns up for Sachin-Jigar's Bollywood garba night. Navratri night four with a production scale that NYC demands — and they deliver.",
    venue: "Hammerstein Ballroom", city: "New York", state: "NY",
    date: "Oct 05, 2026", dateISO: "2026-10-05", time: "8:00 PM",
    category: "Fusion Garba", price: 85, priceVIP: 160, totalTickets: 2000, soldTickets: 1840,
    tags: ["Bollywood", "Fusion", "NYC", "High-Production"], isNavratri: true, navratriNight: 4,
  },
  {
    id: "sj-04", title: "Sachin-Jigar — Bay Area Fusion Garba", artist: "Sachin-Jigar", artistSlug: "sachin-jigar",
    description: "Silicon Valley celebrates Navratri night five with Sachin-Jigar. Bollywood meets garba in a night that the Bay Area tech and cultural community turns out for en masse.",
    venue: "Bill Graham Civic Auditorium", city: "San Francisco", state: "CA",
    date: "Oct 06, 2026", dateISO: "2026-10-06", time: "7:30 PM",
    category: "Fusion Garba", price: 75, priceVIP: 140, totalTickets: 2500, soldTickets: 2125,
    tags: ["Bollywood", "Fusion", "San Francisco", "Navratri"], isNavratri: true, navratriNight: 5,
  },
  {
    id: "sj-05", title: "Sachin-Jigar — Houston Bollywood Garba", artist: "Sachin-Jigar", artistSlug: "sachin-jigar",
    description: "Houston celebrates Navratri night six with Sachin-Jigar's Bollywood garba extravaganza. Their biggest hits performed live with a full backing band.",
    venue: "House of Blues Houston", city: "Houston", state: "TX",
    date: "Oct 07, 2026", dateISO: "2026-10-07", time: "7:30 PM",
    category: "Fusion Garba", price: 65, priceVIP: 120, totalTickets: 2000, soldTickets: 1660,
    tags: ["Bollywood", "Fusion", "Houston", "Navratri"], isNavratri: true, navratriNight: 6,
  },
  {
    id: "sj-06", title: "Sachin-Jigar — Dallas Fusion Night", artist: "Sachin-Jigar", artistSlug: "sachin-jigar",
    description: "Dallas's premier fusion garba night with Sachin-Jigar. Navratri night seven — Bollywood's biggest garba composers performing their own hits live.",
    venue: "House of Blues Dallas", city: "Dallas", state: "TX",
    date: "Oct 08, 2026", dateISO: "2026-10-08", time: "8:00 PM",
    category: "Fusion Garba", price: 65, priceVIP: 120, totalTickets: 2000, soldTickets: 1580,
    tags: ["Bollywood", "Fusion", "Dallas", "High-Production"], isNavratri: true, navratriNight: 7,
  },
  {
    id: "sj-07", title: "Sachin-Jigar — Atlanta Bollywood Garba", artist: "Sachin-Jigar", artistSlug: "sachin-jigar",
    description: "Atlanta's Bollywood garba night eight with Sachin-Jigar. The composers who soundtracked a generation of Navratri, now performing live before the final night.",
    venue: "Atlanta Symphony Hall", city: "Atlanta", state: "GA",
    date: "Oct 09, 2026", dateISO: "2026-10-09", time: "7:30 PM",
    category: "Fusion Garba", price: 62, priceVIP: 115, totalTickets: 2000, soldTickets: 1540,
    tags: ["Bollywood", "Fusion", "Atlanta", "Navratri"], isNavratri: true, navratriNight: 8,
  },
  {
    id: "sj-08", title: "Sachin-Jigar — LA Fusion Garba Night", artist: "Sachin-Jigar", artistSlug: "sachin-jigar",
    description: "Los Angeles celebrates Navratri's final night with Sachin-Jigar's closing Bollywood garba spectacular. A production unlike anything outside of Mumbai.",
    venue: "The Novo", city: "Los Angeles", state: "CA",
    date: "Oct 10, 2026", dateISO: "2026-10-10", time: "8:00 PM",
    category: "Fusion Garba", price: 78, priceVIP: 145, totalTickets: 2000, soldTickets: 1800,
    tags: ["Bollywood", "Fusion", "Los Angeles", "Night Nine"], isNavratri: true, navratriNight: 9,
  },

  // ── PARTHIV GOHIL (7 events) ─────────────────────────────────────────────────
  {
    id: "pg-01", title: "Parthiv Gohil — Edison Navratri Night", artist: "Parthiv Gohil", artistSlug: "parthiv-gohil",
    description: "Playback singing legend Parthiv Gohil brings his signature garba vocals to Edison for Navratri night one. Emotional, powerful, and unforgettable.",
    venue: "Raritan Center", city: "Edison", state: "NJ",
    date: "Oct 02, 2026", dateISO: "2026-10-02", time: "7:30 PM",
    category: "Garba", price: 55, priceVIP: 100, totalTickets: 1500, soldTickets: 1230,
    tags: ["Playback", "Garba", "NJ", "Cultural"], isNavratri: true, navratriNight: 1,
  },
  {
    id: "pg-02", title: "Parthiv Gohil — Chicago Garba Festival", artist: "Parthiv Gohil", artistSlug: "parthiv-gohil",
    description: "Chicago's garba festival night three features Parthiv Gohil. His playback singing roots give his garba performances an emotional depth that moves every crowd.",
    venue: "Loews Chicago O'Hare", city: "Rosemont", state: "IL",
    date: "Oct 04, 2026", dateISO: "2026-10-04", time: "7:00 PM",
    category: "Garba", price: 50, priceVIP: 95, totalTickets: 1200, soldTickets: 960,
    tags: ["Playback", "Garba", "Chicago", "Navratri"], isNavratri: true, navratriNight: 3,
  },
  {
    id: "pg-03", title: "Parthiv Gohil — NYC Navratri Live", artist: "Parthiv Gohil", artistSlug: "parthiv-gohil",
    description: "New York's Navratri night four with Parthiv Gohil. His garba performances are concerts as much as cultural events — the emotion in his voice is unmatched.",
    venue: "Town Hall NYC", city: "New York", state: "NY",
    date: "Oct 05, 2026", dateISO: "2026-10-05", time: "8:00 PM",
    category: "Garba", price: 72, priceVIP: 135, totalTickets: 1000, soldTickets: 870,
    tags: ["Playback", "Garba", "NYC", "Emotional"], isNavratri: true, navratriNight: 4,
  },
  {
    id: "pg-04", title: "Parthiv Gohil — Bay Area Garba Utsav", artist: "Parthiv Gohil", artistSlug: "parthiv-gohil",
    description: "San Jose's Navratri night five with Parthiv Gohil. A garba utsav that doubles as a musical journey — his classical training elevates every garba circle.",
    venue: "California Theatre", city: "San Jose", state: "CA",
    date: "Oct 06, 2026", dateISO: "2026-10-06", time: "7:30 PM",
    category: "Garba", price: 60, priceVIP: 112, totalTickets: 1200, soldTickets: 1008,
    tags: ["Playback", "Garba", "Bay Area", "Cultural"], isNavratri: true, navratriNight: 5,
  },
  {
    id: "pg-05", title: "Parthiv Gohil — Houston Navratri Night", artist: "Parthiv Gohil", artistSlug: "parthiv-gohil",
    description: "Houston's Navratri night six with Parthiv Gohil. The playback legend brings garba to life with classical depth and Bollywood energy in equal measure.",
    venue: "Wortham Theater Center", city: "Houston", state: "TX",
    date: "Oct 07, 2026", dateISO: "2026-10-07", time: "7:30 PM",
    category: "Garba", price: 55, priceVIP: 102, totalTickets: 1500, soldTickets: 1140,
    tags: ["Playback", "Garba", "Houston", "Cultural"], isNavratri: true, navratriNight: 6,
  },
  {
    id: "pg-06", title: "Parthiv Gohil — Dallas Garba Festival", artist: "Parthiv Gohil", artistSlug: "parthiv-gohil",
    description: "Dallas celebrates Navratri night seven with Parthiv Gohil. His garba festival blends classical Indian vocals with high-energy folk garba — an experience for all.",
    venue: "Eisemann Center", city: "Richardson", state: "TX",
    date: "Oct 08, 2026", dateISO: "2026-10-08", time: "7:00 PM",
    category: "Garba", price: 52, priceVIP: 98, totalTickets: 1200, soldTickets: 936,
    tags: ["Playback", "Garba", "Dallas", "Cultural"], isNavratri: true, navratriNight: 7,
  },
  {
    id: "pg-07", title: "Parthiv Gohil — Atlanta Navratri Live", artist: "Parthiv Gohil", artistSlug: "parthiv-gohil",
    description: "Atlanta's Navratri night eight with Parthiv Gohil. The penultimate night of the season — his most emotionally charged garba performance leads into the final night.",
    venue: "Cobb Energy Performing Arts Centre", city: "Atlanta", state: "GA",
    date: "Oct 09, 2026", dateISO: "2026-10-09", time: "7:30 PM",
    category: "Garba", price: 52, priceVIP: 98, totalTickets: 1200, soldTickets: 924,
    tags: ["Playback", "Garba", "Atlanta", "Cultural"], isNavratri: true, navratriNight: 8,
  },
];
