// ── Platform email registry ──────────────────────────────────────────────────
// One transparent catalog of every Rameelo email: what it is, who it's for,
// how it fires (automatic vs manual), and whether it's live yet. Powers the
// admin Emails page. When you ship a new email, add/flip an entry here.

export type EmailTrigger = "automatic" | "manual" | "both";
export type EmailStatus = "live" | "planned";
export type EmailCategory = "Member" | "Orders & Tickets" | "Organizer" | "Payments" | "Platform";

export type EmailDef = {
  key: string;
  name: string;
  description: string;
  audience: string;
  category: EmailCategory;
  status: EmailStatus;
  trigger: EmailTrigger;
  fires: string; // plain-language: when/how it sends
};

export const EMAIL_REGISTRY: EmailDef[] = [
  {
    key: "welcome",
    name: "Welcome email",
    description: "Warm intro inviting a new member to log in, explore Garba 2026 events, buy tickets, and start their Garba Passport.",
    audience: "New members",
    category: "Member",
    status: "live",
    trigger: "both",
    fires: "Automatically on account creation · Manual resend from a user's detail page",
  },
  {
    key: "org-invite",
    name: "Organization invite",
    description: "Invites someone to join an organization's team, with a claim-on-login link.",
    audience: "Organizers",
    category: "Organizer",
    status: "live",
    trigger: "automatic",
    fires: "When an organizer or admin invites a team member",
  },
  {
    key: "password-reset",
    name: "Password reset",
    description: "A secure link (valid 24 hours) for a member to set a new password — branded, not Supabase's default email.",
    audience: "Members",
    category: "Member",
    status: "live",
    trigger: "manual",
    fires: "Triggered by an admin from a user's detail page",
  },
  {
    key: "login-code",
    name: "Sign-in / sign-up code",
    description: "A 6-digit one-time code for passwordless sign-in and sign-up. Expires in 30 minutes; the member enters it to authenticate — no password to remember.",
    audience: "Members",
    category: "Member",
    status: "live",
    trigger: "automatic",
    fires: "When a member requests a sign-in or sign-up code (enters their email)",
  },

  // ── Planned (not yet built) ──
  {
    key: "group-created",
    name: "Group link created",
    description: "Sends the group's creator their shareable link, explains how group orders work, and (when the event has discounts) encourages hitting the headcount for bigger savings.",
    audience: "Members",
    category: "Orders & Tickets",
    status: "live",
    trigger: "automatic",
    fires: "When someone creates a group order link",
  },
  {
    key: "group-joined",
    name: "Group member joined",
    description: "Notifies the group host when someone joins their group link, with the event info and a link to the group page.",
    audience: "Members",
    category: "Orders & Tickets",
    status: "live",
    trigger: "automatic",
    fires: "When someone joins a group order link",
  },
  {
    key: "group-reminder",
    name: "Group reminder — invite more",
    description: "A follow-up to each member of a group, with their group's live progress (members, % to goal, discount needed) and the event details, nudging them to invite more friends. One clear CTA to the group page. Sent by an admin from an event's Groups tab; capped to once per person every 7 days.",
    audience: "Members",
    category: "Orders & Tickets",
    status: "live",
    trigger: "manual",
    fires: "When an admin sends group reminders from an event's Groups tab",
  },
  {
    key: "group-ticket-claim",
    name: "Group ticket claim",
    description: "Tells a group member that someone paid for the group and reserved tickets for them, with a link to sign in / create an account and claim them.",
    audience: "Buyers",
    category: "Orders & Tickets",
    status: "live",
    trigger: "automatic",
    fires: "When one person checks out a group order — each other member gets a claim link",
  },
  {
    key: "order-confirmation",
    name: "Order confirmation & receipt",
    description: "Receipt after a purchase: pricing breakdown, total tickets, event summary with directions, and links to view tickets in the portal (account required) and buy more.",
    audience: "Buyers",
    category: "Orders & Tickets",
    status: "live",
    trigger: "both",
    fires: "Automatically on a confirmed order · Manual resend from an order's detail page",
  },
  {
    key: "tickets-pending",
    name: "Tickets reserved (payment pending)",
    description: "Sent after an ACH/bank checkout while the transfer clears: tickets are reserved but not yet valid, and QR codes appear once payment settles (2–5 business days).",
    audience: "Buyers",
    category: "Orders & Tickets",
    status: "live",
    trigger: "automatic",
    fires: "On a bank/ACH checkout, before the transfer clears",
  },
  {
    key: "payment-failed",
    name: "Payment failed",
    description: "Tells a buyer their payment didn't go through (most often a returned bank/ACH transfer caught after checkout) — their order was canceled, tickets aren't valid, and how to retry.",
    audience: "Buyers",
    category: "Orders & Tickets",
    status: "live",
    trigger: "automatic",
    fires: "When the Stripe webhook reports a payment_intent.payment_failed / canceled",
  },
  {
    key: "order-team-notification",
    name: "New order — team alert",
    description: "Notifies an event's organizing team (org owners/admins + the event creator) on every new order, with the buyer's first name, ticket count, tier, payment type (card vs ACH, with an ACH 'QR pending until cleared' note), event summary, and a small event banner.",
    audience: "Organizers",
    category: "Organizer",
    status: "live",
    trigger: "both",
    fires: "Automatically on every confirmed, non-test order · Manual resend from an order's detail page",
  },
  {
    key: "order-admin-notification",
    name: "New order — admin alert",
    description: "Detailed internal record sent to platform admins on every new order: full buyer contact (first/last name, email, phone), ticket count & tier, event/artist/date, the face-value price breakdown, buyer-paid Rameelo & card fees, and Rameelo's effective profit after Stripe's processing cost. Admins can opt out per event from the event's admin detail page.",
    audience: "Admins",
    category: "Platform",
    status: "live",
    trigger: "automatic",
    fires: "Automatically on every confirmed, non-test order — to each admin still subscribed for that event",
  },
  {
    key: "comp-ticket",
    name: "Complimentary tickets",
    description: "Tells someone an organizer gifted them free tickets. Branches on whether they already have a Rameelo account — log in to find the tickets waiting, or create a free account with the same email and have the tickets attach automatically. No payment, no claim code.",
    audience: "Buyers",
    category: "Orders & Tickets",
    status: "live",
    trigger: "automatic",
    fires: "When an organizer issues comp tickets from an event's Comp Tickets page",
  },
  {
    key: "event-reminder",
    name: "Event reminder",
    description: "A nudge a few days before an event the member holds tickets to.",
    audience: "Buyers",
    category: "Orders & Tickets",
    status: "planned",
    trigger: "automatic",
    fires: "Scheduled before the event date",
  },
  {
    key: "ticket-transfer",
    name: "Ticket transfer",
    description: "Tells someone a Rameelo member sent them ticket(s), with a one-tap claim link. Personalized to name the sender and greet the recipient, it branches on whether they already have an account — log in and accept, or create a free account with the same email (step-by-step, plus a link to the how-to-create-an-account help article) so the tickets attach automatically.",
    audience: "Members",
    category: "Orders & Tickets",
    status: "live",
    trigger: "automatic",
    fires: "Automatically when a member transfers a ticket from My Tickets",
  },
  {
    key: "ticket-transfer-declined",
    name: "Ticket transfer declined",
    description: "Closes the loop on a transfer: when the recipient declines, the original sender gets a reassuring note that their tickets are back in their wallet (nothing lost) with a one-tap CTA to send them to someone else instead.",
    audience: "Members",
    category: "Orders & Tickets",
    status: "live",
    trigger: "automatic",
    fires: "Automatically when a transfer recipient declines",
  },
  {
    key: "tickets-live",
    name: "Tickets-now-live alert",
    description: "A conversion email to an event's interest list when tickets go on sale: a warm thank-you for their interest, the event at a glance, gentle urgency, and one CTA into the event page to buy. Personalized per recipient (first name + the quantity they wanted), and anyone who already purchased is skipped.",
    audience: "Interested fans",
    category: "Orders & Tickets",
    status: "live",
    trigger: "manual",
    fires: "When an admin clicks “Notify interested people” in an event's Interest tab",
  },
  {
    key: "daily-summary",
    name: "Daily activity summary",
    description: "A daily digest to all platform admins for the prior Pacific-time day: new users, online orders, tickets, ticket revenue, platform fees, total collected, offline/manual sales, comp tickets, and an event-by-event sales breakdown — enough context to decide what to focus on.",
    audience: "Admins",
    category: "Platform",
    status: "live",
    trigger: "both",
    fires: "Automatically each midnight (Pacific) via cron · Manual send for any date from the admin Dashboard",
  },
  {
    key: "payout-status",
    name: "Payout status",
    description: "Updates an organizer when a payout request is approved, paid, or declined.",
    audience: "Organizers",
    category: "Payments",
    status: "planned",
    trigger: "automatic",
    fires: "On a payout status change",
  },
  {
    key: "refund-dispute",
    name: "Refund & dispute notice",
    description: "Notifies the buyer and organizer on refunds, chargebacks, and dispute updates.",
    audience: "Members & Organizers",
    category: "Payments",
    status: "planned",
    trigger: "automatic",
    fires: "On a refund or dispute event",
  },
  {
    key: "new-user-signup",
    name: "New user signup alert",
    description: "Notifies all platform admins when someone registers a Rameelo account, with the new member's name, email, phone, and location so an admin can reach out directly.",
    audience: "Admins",
    category: "Platform",
    status: "live",
    trigger: "automatic",
    fires: "Automatically when a user creates an account",
  },
  {
    key: "marketing-blast",
    name: "Marketing blast",
    description: "A marketing email to a targeted group (by tag, upload batch, location, or past-event attendance) about an upcoming event, sent from a selectable, ready-made template — Tickets are live, Selling fast, Final call, We saved you a spot, or a Custom message. Each lists the event's ticket tiers & prices and builds urgency off the sale-close date, with one 'Get tickets' CTA. Admins can preview and send a test before blasting. Honors per-user marketing opt-out and includes one-click unsubscribe. Sent from hello@.",
    audience: "Members",
    category: "Platform",
    status: "live",
    trigger: "manual",
    fires: "When an admin sends a blast from the Email Blast tool",
  },
  {
    key: "sponsorship-inquiry",
    name: "Sponsorship inquiry alert",
    description: "Notifies all platform admins, with the full form details, when someone submits the /sponsor advertising form.",
    audience: "Admins",
    category: "Platform",
    status: "live",
    trigger: "automatic",
    fires: "When a sponsorship inquiry is submitted",
  },
  {
    key: "promotion-entry",
    name: "Promotion entry alert",
    description: "Notifies all platform admins when someone enters a giveaway/raffle promotion, with the entrant's name, email, phone, and location, plus a running entry total. Only fires for genuinely new entries (duplicate emails don't re-notify).",
    audience: "Admins",
    category: "Platform",
    status: "live",
    trigger: "automatic",
    fires: "When a new promotion entry is submitted",
  },
  {
    key: "event-interest",
    name: "Event interest alert",
    description: "Notifies all platform admins when someone submits the interest (\"notify me\") form on an event that isn't selling tickets on Rameelo yet — with the submitter's name, email, phone, city, tickets wanted, and message, plus the event and a running interest total. Surfaces which not-yet-live events are getting traction.",
    audience: "Admins",
    category: "Platform",
    status: "live",
    trigger: "automatic",
    fires: "When an interest form is submitted for a non-selling event",
  },
  {
    key: "onboarding-invite",
    name: "Organizer onboarding link",
    description: "Emails a lead the onboarding questionnaire link (currently copy-pasted from the admin org page).",
    audience: "Organizer leads",
    category: "Organizer",
    status: "planned",
    trigger: "manual",
    fires: "Sent by an admin from the organization page",
  },
  {
    key: "onboarding-signed",
    name: "Organizer agreement signed — admin alert",
    description: "Notifies every platform admin when an organizer completes onboarding and signs the Rameelo Organizer Agreement: who signed and when, the agreement version they bound, and the key facts from their submission (organization, primary contact, email/phone, website & socials, location, event and document counts) with a link to review the org in admin.",
    audience: "Admins",
    category: "Platform",
    status: "live",
    trigger: "automatic",
    fires: "Automatically when an organizer submits and signs the onboarding questionnaire",
  },
];
